package inner_product

import (
	"log/slog"
	"slices"

	"github.com/QinYuuuu/abvss/pkg"
	"go.dedis.ch/kyber/v4"
)

type Prover struct {
	v   kyber.Scalar
	crs *CRS
}

func (crs *CRS) InnerProductProveInput(a []kyber.Scalar) (kyber.Scalar, kyber.Point) {
	v, err := pkg.DotProductKyber(crs.yVec, a)
	if err != nil {
		slog.Error("Prover Input DotProduct", slog.Any("error", err))
	}
	// h^v
	result := crs.group.Point().Mul(v, crs.h)
	// A = (g[]^a[]) * (h^v)
	for i, g := range crs.gVec {
		tmp := crs.group.Point().Mul(a[i], g)
		result = result.Add(result, tmp)
	}
	return v, result
}

func (crs *CRS) RecursiveProve(gVec []kyber.Point, h, P kyber.Point, aVec, yVec, zVec []kyber.Scalar, n int) {
	aLen := len(aVec)
	gLen := len(gVec)
	if aLen != len(yVec) {
		return
	}
	// step 1 Prover send aVec to Verifier
	if n == 1 {
		return
	}

	// step 2
	// Prover send aVec[n] to Verifier
	if n%2 == 1 {
		aNeg := crs.group.Scalar().Neg(aVec[n-1])
		tmp1 := crs.group.Point().Mul(aNeg, gVec[n-1])
		tmp2 := crs.group.Point().Mul(crs.group.Scalar().Mul(aNeg, yVec[n-1]), h)
		P = crs.group.Point().Add(crs.group.Point().Add(tmp1, tmp2), P)

		aVec = aVec[:aLen-1]
		yVec = yVec[:aLen-1]
		gVec = gVec[:gLen-1]
		n = n - 1
	}
	n1 := n / 2

	// step 3
	cl, _ := pkg.DotProductKyber(aVec[:n1], yVec[n1:])
	cr, _ := pkg.DotProductKyber(aVec[:n1], yVec[n1:])
	L := crs.group.Point().Mul(cl, h)
	R := crs.group.Point().Mul(cr, h)
	for i := 0; i < n1; i++ {
		tmp := crs.group.Point().Mul(aVec[:n1][i], gVec[n1:][i])
		L = crs.group.Point().Add(tmp, L)
		tmp = crs.group.Point().Mul(aVec[n1:][i], gVec[:n1][i])
		R = crs.group.Point().Add(tmp, R)
	}

	// z is the challenge value
	z := zVec[0]
	zVec1 := zVec[1:]
	zInv := crs.group.Scalar().Inv(z)
	// step 5, step 6
	gVec1 := make([]kyber.Point, n1)
	aVec1 := make([]kyber.Scalar, n1)
	yVec1 := make([]kyber.Scalar, n1)
	for i := 0; i < n1; i++ {
		left := crs.group.Scalar().Mul(z, yVec[:n1][i])
		right := crs.group.Scalar().Mul(zInv, yVec[:n1][i])
		yVec1[i] = crs.group.Scalar().Add(left, right)

		left1 := crs.group.Point().Mul(zInv, gVec[:n1][i])
		right1 := crs.group.Point().Mul(z, gVec[n1:][i])
		gVec1[i] = crs.group.Point().Add(left1, right1)

		// only prover compute
		left = crs.group.Scalar().Mul(z, aVec[:n1][i])
		right = crs.group.Scalar().Mul(zInv, aVec[n1:][i])
		aVec1[i] = crs.group.Scalar().Add(left, right)
	}

	z2 := crs.group.Scalar().Mul(z, z)
	z2Inv := crs.group.Scalar().Inv(z2)

	Lz2 := crs.group.Point().Mul(z2, L)
	Rz2Inv := crs.group.Point().Mul(z2Inv, R)
	P1 := crs.group.Point().Add(crs.group.Point().Add(P, Lz2), Rz2Inv)
	crs.RecursiveProve(gVec1, h, P1, aVec1, yVec1, zVec1, n1)
	return
}

func (crs *CRS) NonInteractReduceProve(P kyber.Point, v kyber.Scalar, aVec []kyber.Scalar) (*Proof, error) {
	// copy from common reference string
	gVec := make([]kyber.Point, len(crs.gVec))
	copy(gVec, crs.gVec)
	h := crs.h
	yVec := make([]kyber.Scalar, len(crs.yVec))
	copy(yVec, crs.yVec)
	n := crs.n
	// return values
	LVec := make([]kyber.Point, 0)
	RVec := make([]kyber.Point, 0)
	aVecToSend := make([]kyber.Scalar, 0)
	// step 1 Prover send aVec to Verifier
	for n > 1 {
		if n%2 == 1 {
			// step 2
			// Prover send aVec[-1] to Verifier
			a := aVec[n-1]
			// slog.Info("Prover		", slog.Any("n", n), slog.Any("a to verifier", a.String()))
			aVecToSend = append(aVecToSend, a)
			y := yVec[n-1]
			// slog.Info("Prover		", slog.Any("n", n), slog.String("y[-1]", y.String()))
			// A = A * (g[-1]^(-a[-1])) * (h^(-a[-1] * y[-1]))
			aNeg := crs.group.Scalar().Neg(a)
			tmp1 := crs.group.Point().Mul(aNeg, gVec[n-1])
			tmp2 := crs.group.Point().Mul(crs.group.Scalar().Mul(aNeg, y), h)
			P = crs.group.Point().Add(crs.group.Point().Add(tmp1, tmp2), P)
			// slog.Info("Prover		", slog.Any("n", n), slog.String("p in n is odd", P.String()))
			aVec = aVec[:n-1]
			yVec = yVec[:n-1]
			gVec = gVec[:n-1]
			n = n - 1

			// for debug
			/*{
				v = crs.group.Scalar().Add(v, crs.group.Scalar().Mul(aNeg, y))
				power, _ := pkg.DotProductKyber(aVec, yVec)
				tmp := crs.group.Point().Mul(power, h)
				pwant, _ := pkg.DotProductExpKyber(gVec, aVec)
				pwant = crs.group.Point().Add(pwant, tmp)
				slog.Info("Prover		", slog.Any("verify in n is odd", pwant.String() == P.String()))
			}*/
		}
		n1 := n / 2

		// step 3
		cl, _ := pkg.DotProductKyber(aVec[:n1], yVec[n1:])
		cr, _ := pkg.DotProductKyber(aVec[n1:], yVec[:n1])
		L := crs.group.Point().Mul(cl, h)
		R := crs.group.Point().Mul(cr, h)
		for i := int64(0); i < n1; i++ {
			tmp := crs.group.Point().Mul(aVec[:n1][i], gVec[n1:][i])
			L = crs.group.Point().Add(tmp, L)
			tmp = crs.group.Point().Mul(aVec[n1:][i], gVec[:n1][i])
			R = crs.group.Point().Add(tmp, R)
		}
		LVec = append(LVec, L)
		RVec = append(RVec, R)
		// z is the challenge value, generated by H(L,R)
		z := crs.generateRandom(L, R)
		// slog.Info("Prover nonInteractProve z marshal", slog.Any("n", n), slog.Any("z", z.String()))
		zInv := crs.group.Scalar().Inv(z)
		// step 5, step 6
		gVec1 := make([]kyber.Point, n1)
		aVec1 := make([]kyber.Scalar, n1)
		yVec1 := make([]kyber.Scalar, n1)
		for i := int64(0); i < n1; i++ {
			left := crs.group.Scalar().Mul(zInv, yVec[:n1][i])
			right := crs.group.Scalar().Mul(z, yVec[n1:][i])
			yVec1[i] = crs.group.Scalar().Add(left, right)

			left1 := crs.group.Point().Mul(zInv, gVec[:n1][i])
			right1 := crs.group.Point().Mul(z, gVec[n1:][i])
			gVec1[i] = crs.group.Point().Add(left1, right1)

			// only prover compute
			left = crs.group.Scalar().Mul(z, aVec[:n1][i])
			right = crs.group.Scalar().Mul(zInv, aVec[n1:][i])
			aVec1[i] = crs.group.Scalar().Add(left, right)
		}

		z2 := crs.group.Scalar().Mul(z, z)
		z2Inv := crs.group.Scalar().Inv(z2)
		Lz2 := crs.group.Point().Mul(z2, L)
		Rz2Inv := crs.group.Point().Mul(z2Inv, R)
		P1 := crs.group.Point().Add(crs.group.Point().Add(P, Lz2), Rz2Inv)

		// for debug
		/*{
			left, _ := pkg.DotProductKyber(aVec1, yVec1)
			tmp1 := crs.group.Scalar().Mul(cl, z2)
			tmp2 := crs.group.Scalar().Mul(cr, z2Inv)
			right := crs.group.Scalar().Add(crs.group.Scalar().Add(tmp1, tmp2), v)
			slog.Info("Prover nonInteractProve", slog.Any("verify <a',y'> final", left.String() == right.String()))

			left1, _ := pkg.DotProductExpKyber(gVec1, aVec1)
			tmp3 := crs.group.Point().Mul(right, h)
			left1 = crs.group.Point().Add(left1, tmp3)
			right1 := P1
			slog.Info("Prover nonInteractProve", slog.Any("verify A' final", left1.String() == right1.String()))
		}*/

		n = n1
		P = P1
		gVec = gVec1
		aVec = aVec1
		yVec = yVec1
	}
	aVecToSend = append(aVecToSend, aVec...)
	slices.Reverse(aVecToSend)
	// slog.Info("Prover nonInteractProve", slog.Any("final p value", P.String()))
	return &Proof{
		lVec:       LVec,
		rVec:       RVec,
		aVecToSend: aVecToSend,
	}, nil
}

func (crs *CRS) generateRandom(L, R kyber.Point) kyber.Scalar {
	LBytes := []byte(L.String())
	RBytes := []byte(R.String())
	zByte := append(LBytes, RBytes...)

	z := crs.group.Scalar().SetBytes(zByte)
	return z
}
