// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.27.0
// source: message.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	NodeService_RBC_FullMethodName          = "/services.NodeService/RBC"
	NodeService_BroadcastLCM_FullMethodName = "/services.NodeService/BroadcastLCM"
	NodeService_OSV_FullMethodName          = "/services.NodeService/OSV"
)

// NodeServiceClient is the client API for NodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NodeServiceClient interface {
	// Node RPC for reconstruction phase
	RBC(ctx context.Context, in *ShareMsg, opts ...grpc.CallOption) (*AckMsg, error)
	BroadcastLCM(ctx context.Context, in *ShareMsg, opts ...grpc.CallOption) (*AckMsg, error)
	OSV(ctx context.Context, in *OSVMessage, opts ...grpc.CallOption) (*AckMsg, error)
}

type nodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeServiceClient(cc grpc.ClientConnInterface) NodeServiceClient {
	return &nodeServiceClient{cc}
}

func (c *nodeServiceClient) RBC(ctx context.Context, in *ShareMsg, opts ...grpc.CallOption) (*AckMsg, error) {
	out := new(AckMsg)
	err := c.cc.Invoke(ctx, NodeService_RBC_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) BroadcastLCM(ctx context.Context, in *ShareMsg, opts ...grpc.CallOption) (*AckMsg, error) {
	out := new(AckMsg)
	err := c.cc.Invoke(ctx, NodeService_BroadcastLCM_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) OSV(ctx context.Context, in *OSVMessage, opts ...grpc.CallOption) (*AckMsg, error) {
	out := new(AckMsg)
	err := c.cc.Invoke(ctx, NodeService_OSV_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeServiceServer is the server API for NodeService service.
// All implementations must embed UnimplementedNodeServiceServer
// for forward compatibility
type NodeServiceServer interface {
	// Node RPC for reconstruction phase
	RBC(context.Context, *ShareMsg) (*AckMsg, error)
	BroadcastLCM(context.Context, *ShareMsg) (*AckMsg, error)
	OSV(context.Context, *OSVMessage) (*AckMsg, error)
	mustEmbedUnimplementedNodeServiceServer()
}

// UnimplementedNodeServiceServer must be embedded to have forward compatible implementations.
type UnimplementedNodeServiceServer struct {
}

func (UnimplementedNodeServiceServer) RBC(context.Context, *ShareMsg) (*AckMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RBC not implemented")
}
func (UnimplementedNodeServiceServer) BroadcastLCM(context.Context, *ShareMsg) (*AckMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BroadcastLCM not implemented")
}
func (UnimplementedNodeServiceServer) OSV(context.Context, *OSVMessage) (*AckMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OSV not implemented")
}
func (UnimplementedNodeServiceServer) mustEmbedUnimplementedNodeServiceServer() {}

// UnsafeNodeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeServiceServer will
// result in compilation errors.
type UnsafeNodeServiceServer interface {
	mustEmbedUnimplementedNodeServiceServer()
}

func RegisterNodeServiceServer(s grpc.ServiceRegistrar, srv NodeServiceServer) {
	s.RegisterService(&NodeService_ServiceDesc, srv)
}

func _NodeService_RBC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShareMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).RBC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_RBC_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).RBC(ctx, req.(*ShareMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_BroadcastLCM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShareMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).BroadcastLCM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_BroadcastLCM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).BroadcastLCM(ctx, req.(*ShareMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_OSV_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OSVMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).OSV(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_OSV_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).OSV(ctx, req.(*OSVMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// NodeService_ServiceDesc is the grpc.ServiceDesc for NodeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "services.NodeService",
	HandlerType: (*NodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RBC",
			Handler:    _NodeService_RBC_Handler,
		},
		{
			MethodName: "BroadcastLCM",
			Handler:    _NodeService_BroadcastLCM_Handler,
		},
		{
			MethodName: "OSV",
			Handler:    _NodeService_OSV_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "message.proto",
}
