// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.27.0
// source: Message.proto

package protobuf

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Conn_Receive_FullMethodName = "/services.Conn/Receive"
)

// ConnClient is the client API for Conn service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConnClient interface {
	Receive(ctx context.Context, in *TestHelloMessage, opts ...grpc.CallOption) (*TestResMessage, error)
}

type connClient struct {
	cc grpc.ClientConnInterface
}

func NewConnClient(cc grpc.ClientConnInterface) ConnClient {
	return &connClient{cc}
}

func (c *connClient) Receive(ctx context.Context, in *TestHelloMessage, opts ...grpc.CallOption) (*TestResMessage, error) {
	out := new(TestResMessage)
	err := c.cc.Invoke(ctx, Conn_Receive_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConnServer is the server API for Conn service.
// All implementations must embed UnimplementedConnServer
// for forward compatibility
type ConnServer interface {
	Receive(context.Context, *TestHelloMessage) (*TestResMessage, error)
	mustEmbedUnimplementedConnServer()
}

// UnimplementedConnServer must be embedded to have forward compatible implementations.
type UnimplementedConnServer struct {
}

func (UnimplementedConnServer) Receive(context.Context, *TestHelloMessage) (*TestResMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Receive not implemented")
}
func (UnimplementedConnServer) mustEmbedUnimplementedConnServer() {}

// UnsafeConnServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConnServer will
// result in compilation errors.
type UnsafeConnServer interface {
	mustEmbedUnimplementedConnServer()
}

func RegisterConnServer(s grpc.ServiceRegistrar, srv ConnServer) {
	s.RegisterService(&Conn_ServiceDesc, srv)
}

func _Conn_Receive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestHelloMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnServer).Receive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Conn_Receive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnServer).Receive(ctx, req.(*TestHelloMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// Conn_ServiceDesc is the grpc.ServiceDesc for Conn service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Conn_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "services.Conn",
	HandlerType: (*ConnServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Receive",
			Handler:    _Conn_Receive_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Message.proto",
}

const (
	RBC_Receive_FullMethodName = "/services.RBC/Receive"
)

// RBCClient is the client API for RBC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RBCClient interface {
	Receive(ctx context.Context, in *Message, opts ...grpc.CallOption) (*AckMsg, error)
}

type rBCClient struct {
	cc grpc.ClientConnInterface
}

func NewRBCClient(cc grpc.ClientConnInterface) RBCClient {
	return &rBCClient{cc}
}

func (c *rBCClient) Receive(ctx context.Context, in *Message, opts ...grpc.CallOption) (*AckMsg, error) {
	out := new(AckMsg)
	err := c.cc.Invoke(ctx, RBC_Receive_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RBCServer is the server API for RBC service.
// All implementations must embed UnimplementedRBCServer
// for forward compatibility
type RBCServer interface {
	Receive(context.Context, *Message) (*AckMsg, error)
	mustEmbedUnimplementedRBCServer()
}

// UnimplementedRBCServer must be embedded to have forward compatible implementations.
type UnimplementedRBCServer struct {
}

func (UnimplementedRBCServer) Receive(context.Context, *Message) (*AckMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Receive not implemented")
}
func (UnimplementedRBCServer) mustEmbedUnimplementedRBCServer() {}

// UnsafeRBCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RBCServer will
// result in compilation errors.
type UnsafeRBCServer interface {
	mustEmbedUnimplementedRBCServer()
}

func RegisterRBCServer(s grpc.ServiceRegistrar, srv RBCServer) {
	s.RegisterService(&RBC_ServiceDesc, srv)
}

func _RBC_Receive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RBCServer).Receive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RBC_Receive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RBCServer).Receive(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

// RBC_ServiceDesc is the grpc.ServiceDesc for RBC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RBC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "services.RBC",
	HandlerType: (*RBCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Receive",
			Handler:    _RBC_Receive_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Message.proto",
}

const (
	ABVSS_ReceiveShares_FullMethodName    = "/services.ABVSS/ReceiveShares"
	ABVSS_ReceiveLCM_FullMethodName       = "/services.ABVSS/ReceiveLCM"
	ABVSS_ReconstructLCM_FullMethodName   = "/services.ABVSS/ReconstructLCM"
	ABVSS_ReceiveRecShares_FullMethodName = "/services.ABVSS/ReceiveRecShares"
)

// ABVSSClient is the client API for ABVSS service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ABVSSClient interface {
	ReceiveShares(ctx context.Context, in *SharesMsg, opts ...grpc.CallOption) (*AckMsg, error)
	ReceiveLCM(ctx context.Context, in *LCMMsg, opts ...grpc.CallOption) (*AckMsg, error)
	ReconstructLCM(ctx context.Context, in *SKMsg, opts ...grpc.CallOption) (*AckMsg, error)
	ReceiveRecShares(ctx context.Context, in *SKMsg, opts ...grpc.CallOption) (*AckMsg, error)
}

type aBVSSClient struct {
	cc grpc.ClientConnInterface
}

func NewABVSSClient(cc grpc.ClientConnInterface) ABVSSClient {
	return &aBVSSClient{cc}
}

func (c *aBVSSClient) ReceiveShares(ctx context.Context, in *SharesMsg, opts ...grpc.CallOption) (*AckMsg, error) {
	out := new(AckMsg)
	err := c.cc.Invoke(ctx, ABVSS_ReceiveShares_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBVSSClient) ReceiveLCM(ctx context.Context, in *LCMMsg, opts ...grpc.CallOption) (*AckMsg, error) {
	out := new(AckMsg)
	err := c.cc.Invoke(ctx, ABVSS_ReceiveLCM_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBVSSClient) ReconstructLCM(ctx context.Context, in *SKMsg, opts ...grpc.CallOption) (*AckMsg, error) {
	out := new(AckMsg)
	err := c.cc.Invoke(ctx, ABVSS_ReconstructLCM_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBVSSClient) ReceiveRecShares(ctx context.Context, in *SKMsg, opts ...grpc.CallOption) (*AckMsg, error) {
	out := new(AckMsg)
	err := c.cc.Invoke(ctx, ABVSS_ReceiveRecShares_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ABVSSServer is the server API for ABVSS service.
// All implementations must embed UnimplementedABVSSServer
// for forward compatibility
type ABVSSServer interface {
	ReceiveShares(context.Context, *SharesMsg) (*AckMsg, error)
	ReceiveLCM(context.Context, *LCMMsg) (*AckMsg, error)
	ReconstructLCM(context.Context, *SKMsg) (*AckMsg, error)
	ReceiveRecShares(context.Context, *SKMsg) (*AckMsg, error)
	mustEmbedUnimplementedABVSSServer()
}

// UnimplementedABVSSServer must be embedded to have forward compatible implementations.
type UnimplementedABVSSServer struct {
}

func (UnimplementedABVSSServer) ReceiveShares(context.Context, *SharesMsg) (*AckMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReceiveShares not implemented")
}
func (UnimplementedABVSSServer) ReceiveLCM(context.Context, *LCMMsg) (*AckMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReceiveLCM not implemented")
}
func (UnimplementedABVSSServer) ReconstructLCM(context.Context, *SKMsg) (*AckMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReconstructLCM not implemented")
}
func (UnimplementedABVSSServer) ReceiveRecShares(context.Context, *SKMsg) (*AckMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReceiveRecShares not implemented")
}
func (UnimplementedABVSSServer) mustEmbedUnimplementedABVSSServer() {}

// UnsafeABVSSServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ABVSSServer will
// result in compilation errors.
type UnsafeABVSSServer interface {
	mustEmbedUnimplementedABVSSServer()
}

func RegisterABVSSServer(s grpc.ServiceRegistrar, srv ABVSSServer) {
	s.RegisterService(&ABVSS_ServiceDesc, srv)
}

func _ABVSS_ReceiveShares_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SharesMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABVSSServer).ReceiveShares(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ABVSS_ReceiveShares_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABVSSServer).ReceiveShares(ctx, req.(*SharesMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABVSS_ReceiveLCM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LCMMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABVSSServer).ReceiveLCM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ABVSS_ReceiveLCM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABVSSServer).ReceiveLCM(ctx, req.(*LCMMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABVSS_ReconstructLCM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SKMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABVSSServer).ReconstructLCM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ABVSS_ReconstructLCM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABVSSServer).ReconstructLCM(ctx, req.(*SKMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABVSS_ReceiveRecShares_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SKMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABVSSServer).ReceiveRecShares(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ABVSS_ReceiveRecShares_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABVSSServer).ReceiveRecShares(ctx, req.(*SKMsg))
	}
	return interceptor(ctx, in, info, handler)
}

// ABVSS_ServiceDesc is the grpc.ServiceDesc for ABVSS service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ABVSS_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "services.ABVSS",
	HandlerType: (*ABVSSServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReceiveShares",
			Handler:    _ABVSS_ReceiveShares_Handler,
		},
		{
			MethodName: "ReceiveLCM",
			Handler:    _ABVSS_ReceiveLCM_Handler,
		},
		{
			MethodName: "ReconstructLCM",
			Handler:    _ABVSS_ReconstructLCM_Handler,
		},
		{
			MethodName: "ReceiveRecShares",
			Handler:    _ABVSS_ReceiveRecShares_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Message.proto",
}

const (
	OSV_Receive_FullMethodName = "/services.OSV/Receive"
)

// OSVClient is the client API for OSV service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OSVClient interface {
	Receive(ctx context.Context, in *OSVMsg, opts ...grpc.CallOption) (*AckMsg, error)
}

type oSVClient struct {
	cc grpc.ClientConnInterface
}

func NewOSVClient(cc grpc.ClientConnInterface) OSVClient {
	return &oSVClient{cc}
}

func (c *oSVClient) Receive(ctx context.Context, in *OSVMsg, opts ...grpc.CallOption) (*AckMsg, error) {
	out := new(AckMsg)
	err := c.cc.Invoke(ctx, OSV_Receive_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OSVServer is the server API for OSV service.
// All implementations must embed UnimplementedOSVServer
// for forward compatibility
type OSVServer interface {
	Receive(context.Context, *OSVMsg) (*AckMsg, error)
	mustEmbedUnimplementedOSVServer()
}

// UnimplementedOSVServer must be embedded to have forward compatible implementations.
type UnimplementedOSVServer struct {
}

func (UnimplementedOSVServer) Receive(context.Context, *OSVMsg) (*AckMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Receive not implemented")
}
func (UnimplementedOSVServer) mustEmbedUnimplementedOSVServer() {}

// UnsafeOSVServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OSVServer will
// result in compilation errors.
type UnsafeOSVServer interface {
	mustEmbedUnimplementedOSVServer()
}

func RegisterOSVServer(s grpc.ServiceRegistrar, srv OSVServer) {
	s.RegisterService(&OSV_ServiceDesc, srv)
}

func _OSV_Receive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OSVMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OSVServer).Receive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OSV_Receive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OSVServer).Receive(ctx, req.(*OSVMsg))
	}
	return interceptor(ctx, in, info, handler)
}

// OSV_ServiceDesc is the grpc.ServiceDesc for OSV service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OSV_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "services.OSV",
	HandlerType: (*OSVServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Receive",
			Handler:    _OSV_Receive_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Message.proto",
}
