// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.27.0
// source: Message.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TestHelloMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FromID  int64  `protobuf:"varint,1,opt,name=fromID,proto3" json:"fromID,omitempty"`
	DestID  int64  `protobuf:"varint,2,opt,name=destID,proto3" json:"destID,omitempty"`
	Content string `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *TestHelloMessage) Reset() {
	*x = TestHelloMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestHelloMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestHelloMessage) ProtoMessage() {}

func (x *TestHelloMessage) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestHelloMessage.ProtoReflect.Descriptor instead.
func (*TestHelloMessage) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{0}
}

func (x *TestHelloMessage) GetFromID() int64 {
	if x != nil {
		return x.FromID
	}
	return 0
}

func (x *TestHelloMessage) GetDestID() int64 {
	if x != nil {
		return x.DestID
	}
	return 0
}

func (x *TestHelloMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type TestResMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FromID  int64  `protobuf:"varint,1,opt,name=fromID,proto3" json:"fromID,omitempty"`
	DestID  int64  `protobuf:"varint,2,opt,name=destID,proto3" json:"destID,omitempty"`
	Content string `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *TestResMessage) Reset() {
	*x = TestResMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestResMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestResMessage) ProtoMessage() {}

func (x *TestResMessage) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestResMessage.ProtoReflect.Descriptor instead.
func (*TestResMessage) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{1}
}

func (x *TestResMessage) GetFromID() int64 {
	if x != nil {
		return x.FromID
	}
	return 0
}

func (x *TestResMessage) GetDestID() int64 {
	if x != nil {
		return x.DestID
	}
	return 0
}

func (x *TestResMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FromID int64  `protobuf:"varint,1,opt,name=FromID,proto3" json:"FromID,omitempty"`
	DestID int64  `protobuf:"varint,2,opt,name=DestID,proto3" json:"DestID,omitempty"`
	Index  int64  `protobuf:"varint,3,opt,name=Index,proto3" json:"Index,omitempty"`
	Mtype  string `protobuf:"bytes,4,opt,name=Mtype,proto3" json:"Mtype,omitempty"`
	Data   []byte `protobuf:"bytes,5,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{2}
}

func (x *Message) GetFromID() int64 {
	if x != nil {
		return x.FromID
	}
	return 0
}

func (x *Message) GetDestID() int64 {
	if x != nil {
		return x.DestID
	}
	return 0
}

func (x *Message) GetIndex() int64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Message) GetMtype() string {
	if x != nil {
		return x.Mtype
	}
	return ""
}

func (x *Message) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type SharesMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FromID int64    `protobuf:"varint,1,opt,name=fromID,proto3" json:"fromID,omitempty"`
	DestID int64    `protobuf:"varint,2,opt,name=destID,proto3" json:"destID,omitempty"`
	Zi     [][]byte `protobuf:"bytes,3,rep,name=zi,proto3" json:"zi,omitempty"`
	Xi     [][]byte `protobuf:"bytes,4,rep,name=xi,proto3" json:"xi,omitempty"`
}

func (x *SharesMsg) Reset() {
	*x = SharesMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Message_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SharesMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SharesMsg) ProtoMessage() {}

func (x *SharesMsg) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SharesMsg.ProtoReflect.Descriptor instead.
func (*SharesMsg) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{3}
}

func (x *SharesMsg) GetFromID() int64 {
	if x != nil {
		return x.FromID
	}
	return 0
}

func (x *SharesMsg) GetDestID() int64 {
	if x != nil {
		return x.DestID
	}
	return 0
}

func (x *SharesMsg) GetZi() [][]byte {
	if x != nil {
		return x.Zi
	}
	return nil
}

func (x *SharesMsg) GetXi() [][]byte {
	if x != nil {
		return x.Xi
	}
	return nil
}

type LCMMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FromID int64    `protobuf:"varint,1,opt,name=fromID,proto3" json:"fromID,omitempty"`
	DestID int64    `protobuf:"varint,2,opt,name=destID,proto3" json:"destID,omitempty"`
	Lcmi   [][]byte `protobuf:"bytes,3,rep,name=lcmi,proto3" json:"lcmi,omitempty"`
}

func (x *LCMMsg) Reset() {
	*x = LCMMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Message_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LCMMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LCMMsg) ProtoMessage() {}

func (x *LCMMsg) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LCMMsg.ProtoReflect.Descriptor instead.
func (*LCMMsg) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{4}
}

func (x *LCMMsg) GetFromID() int64 {
	if x != nil {
		return x.FromID
	}
	return 0
}

func (x *LCMMsg) GetDestID() int64 {
	if x != nil {
		return x.DestID
	}
	return 0
}

func (x *LCMMsg) GetLcmi() [][]byte {
	if x != nil {
		return x.Lcmi
	}
	return nil
}

type SKMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FromID int64  `protobuf:"varint,1,opt,name=fromID,proto3" json:"fromID,omitempty"`
	DestID int64  `protobuf:"varint,2,opt,name=destID,proto3" json:"destID,omitempty"`
	Sk     []byte `protobuf:"bytes,3,opt,name=sk,proto3" json:"sk,omitempty"`
}

func (x *SKMsg) Reset() {
	*x = SKMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Message_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SKMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SKMsg) ProtoMessage() {}

func (x *SKMsg) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SKMsg.ProtoReflect.Descriptor instead.
func (*SKMsg) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{5}
}

func (x *SKMsg) GetFromID() int64 {
	if x != nil {
		return x.FromID
	}
	return 0
}

func (x *SKMsg) GetDestID() int64 {
	if x != nil {
		return x.DestID
	}
	return 0
}

func (x *SKMsg) GetSk() []byte {
	if x != nil {
		return x.Sk
	}
	return nil
}

type OSVMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FromID int64  `protobuf:"varint,1,opt,name=fromID,proto3" json:"fromID,omitempty"`
	DestID int64  `protobuf:"varint,2,opt,name=destID,proto3" json:"destID,omitempty"`
	Mtype  string `protobuf:"bytes,3,opt,name=mtype,proto3" json:"mtype,omitempty"`
}

func (x *OSVMsg) Reset() {
	*x = OSVMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Message_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OSVMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OSVMsg) ProtoMessage() {}

func (x *OSVMsg) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OSVMsg.ProtoReflect.Descriptor instead.
func (*OSVMsg) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{6}
}

func (x *OSVMsg) GetFromID() int64 {
	if x != nil {
		return x.FromID
	}
	return 0
}

func (x *OSVMsg) GetDestID() int64 {
	if x != nil {
		return x.DestID
	}
	return 0
}

func (x *OSVMsg) GetMtype() string {
	if x != nil {
		return x.Mtype
	}
	return ""
}

type AckMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AckMsg) Reset() {
	*x = AckMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Message_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AckMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckMsg) ProtoMessage() {}

func (x *AckMsg) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckMsg.ProtoReflect.Descriptor instead.
func (*AckMsg) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{7}
}

var File_Message_proto protoreflect.FileDescriptor

var file_Message_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x08, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x22, 0x5c, 0x0a, 0x10, 0x54, 0x65, 0x73,
	0x74, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x66, 0x72, 0x6f, 0x6d, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x66,
	0x72, 0x6f, 0x6d, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x73, 0x74, 0x49, 0x44, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x64, 0x65, 0x73, 0x74, 0x49, 0x44, 0x12, 0x18, 0x0a,
	0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x5a, 0x0a, 0x0e, 0x54, 0x65, 0x73, 0x74, 0x52,
	0x65, 0x73, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x72, 0x6f,
	0x6d, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x66, 0x72, 0x6f, 0x6d, 0x49,
	0x44, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x73, 0x74, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x64, 0x65, 0x73, 0x74, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x22, 0x79, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x46, 0x72, 0x6f, 0x6d, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x46, 0x72, 0x6f, 0x6d, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x44, 0x65, 0x73, 0x74, 0x49, 0x44,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x44, 0x65, 0x73, 0x74, 0x49, 0x44, 0x12, 0x14,
	0x0a, 0x05, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x49,
	0x6e, 0x64, 0x65, 0x78, 0x12, 0x14, 0x0a, 0x05, 0x4d, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x4d, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61,
	0x74, 0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x22, 0x5b,
	0x0a, 0x09, 0x53, 0x68, 0x61, 0x72, 0x65, 0x73, 0x4d, 0x73, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x66,
	0x72, 0x6f, 0x6d, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x66, 0x72, 0x6f,
	0x6d, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x73, 0x74, 0x49, 0x44, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x64, 0x65, 0x73, 0x74, 0x49, 0x44, 0x12, 0x0e, 0x0a, 0x02, 0x7a,
	0x69, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x02, 0x7a, 0x69, 0x12, 0x0e, 0x0a, 0x02, 0x78,
	0x69, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x02, 0x78, 0x69, 0x22, 0x4c, 0x0a, 0x06, 0x4c,
	0x43, 0x4d, 0x4d, 0x73, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x72, 0x6f, 0x6d, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x66, 0x72, 0x6f, 0x6d, 0x49, 0x44, 0x12, 0x16, 0x0a,
	0x06, 0x64, 0x65, 0x73, 0x74, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x64,
	0x65, 0x73, 0x74, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x63, 0x6d, 0x69, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0c, 0x52, 0x04, 0x6c, 0x63, 0x6d, 0x69, 0x22, 0x47, 0x0a, 0x05, 0x53, 0x4b, 0x4d,
	0x73, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x72, 0x6f, 0x6d, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x66, 0x72, 0x6f, 0x6d, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65,
	0x73, 0x74, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x64, 0x65, 0x73, 0x74,
	0x49, 0x44, 0x12, 0x0e, 0x0a, 0x02, 0x73, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02,
	0x73, 0x6b, 0x22, 0x4e, 0x0a, 0x06, 0x4f, 0x53, 0x56, 0x4d, 0x73, 0x67, 0x12, 0x16, 0x0a, 0x06,
	0x66, 0x72, 0x6f, 0x6d, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x66, 0x72,
	0x6f, 0x6d, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x73, 0x74, 0x49, 0x44, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x64, 0x65, 0x73, 0x74, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05,
	0x6d, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x74, 0x79,
	0x70, 0x65, 0x22, 0x08, 0x0a, 0x06, 0x41, 0x63, 0x6b, 0x4d, 0x73, 0x67, 0x32, 0x49, 0x0a, 0x04,
	0x43, 0x6f, 0x6e, 0x6e, 0x12, 0x41, 0x0a, 0x07, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x12,
	0x1a, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x48,
	0x65, 0x6c, 0x6c, 0x6f, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x18, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x00, 0x32, 0x37, 0x0a, 0x03, 0x52, 0x42, 0x43, 0x12, 0x30,
	0x0a, 0x07, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x12, 0x11, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x73, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x10, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x41, 0x63, 0x6b, 0x4d, 0x73, 0x67, 0x22, 0x00,
	0x32, 0xe5, 0x01, 0x0a, 0x05, 0x41, 0x42, 0x56, 0x53, 0x53, 0x12, 0x38, 0x0a, 0x0d, 0x52, 0x65,
	0x63, 0x65, 0x69, 0x76, 0x65, 0x53, 0x68, 0x61, 0x72, 0x65, 0x73, 0x12, 0x13, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x53, 0x68, 0x61, 0x72, 0x65, 0x73, 0x4d, 0x73, 0x67,
	0x1a, 0x10, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x41, 0x63, 0x6b, 0x4d,
	0x73, 0x67, 0x22, 0x00, 0x12, 0x32, 0x0a, 0x0a, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x4c,
	0x43, 0x4d, 0x12, 0x10, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x4c, 0x43,
	0x4d, 0x4d, 0x73, 0x67, 0x1a, 0x10, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e,
	0x41, 0x63, 0x6b, 0x4d, 0x73, 0x67, 0x22, 0x00, 0x12, 0x35, 0x0a, 0x0e, 0x52, 0x65, 0x63, 0x6f,
	0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x4c, 0x43, 0x4d, 0x12, 0x0f, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x53, 0x4b, 0x4d, 0x73, 0x67, 0x1a, 0x10, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x41, 0x63, 0x6b, 0x4d, 0x73, 0x67, 0x22, 0x00, 0x12,
	0x37, 0x0a, 0x10, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x52, 0x65, 0x63, 0x53, 0x68, 0x61,
	0x72, 0x65, 0x73, 0x12, 0x0f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x53,
	0x4b, 0x4d, 0x73, 0x67, 0x1a, 0x10, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e,
	0x41, 0x63, 0x6b, 0x4d, 0x73, 0x67, 0x22, 0x00, 0x32, 0x36, 0x0a, 0x03, 0x4f, 0x53, 0x56, 0x12,
	0x2f, 0x0a, 0x07, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x12, 0x10, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x4f, 0x53, 0x56, 0x4d, 0x73, 0x67, 0x1a, 0x10, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x41, 0x63, 0x6b, 0x4d, 0x73, 0x67, 0x22, 0x00,
	0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Message_proto_rawDescOnce sync.Once
	file_Message_proto_rawDescData = file_Message_proto_rawDesc
)

func file_Message_proto_rawDescGZIP() []byte {
	file_Message_proto_rawDescOnce.Do(func() {
		file_Message_proto_rawDescData = protoimpl.X.CompressGZIP(file_Message_proto_rawDescData)
	})
	return file_Message_proto_rawDescData
}

var file_Message_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_Message_proto_goTypes = []interface{}{
	(*TestHelloMessage)(nil), // 0: services.TestHelloMessage
	(*TestResMessage)(nil),   // 1: services.TestResMessage
	(*Message)(nil),          // 2: services.Message
	(*SharesMsg)(nil),        // 3: services.SharesMsg
	(*LCMMsg)(nil),           // 4: services.LCMMsg
	(*SKMsg)(nil),            // 5: services.SKMsg
	(*OSVMsg)(nil),           // 6: services.OSVMsg
	(*AckMsg)(nil),           // 7: services.AckMsg
}
var file_Message_proto_depIdxs = []int32{
	0, // 0: services.Conn.Receive:input_type -> services.TestHelloMessage
	2, // 1: services.RBC.Receive:input_type -> services.Message
	3, // 2: services.ABVSS.ReceiveShares:input_type -> services.SharesMsg
	4, // 3: services.ABVSS.ReceiveLCM:input_type -> services.LCMMsg
	5, // 4: services.ABVSS.ReconstructLCM:input_type -> services.SKMsg
	5, // 5: services.ABVSS.ReceiveRecShares:input_type -> services.SKMsg
	6, // 6: services.OSV.Receive:input_type -> services.OSVMsg
	1, // 7: services.Conn.Receive:output_type -> services.TestResMessage
	7, // 8: services.RBC.Receive:output_type -> services.AckMsg
	7, // 9: services.ABVSS.ReceiveShares:output_type -> services.AckMsg
	7, // 10: services.ABVSS.ReceiveLCM:output_type -> services.AckMsg
	7, // 11: services.ABVSS.ReconstructLCM:output_type -> services.AckMsg
	7, // 12: services.ABVSS.ReceiveRecShares:output_type -> services.AckMsg
	7, // 13: services.OSV.Receive:output_type -> services.AckMsg
	7, // [7:14] is the sub-list for method output_type
	0, // [0:7] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Message_proto_init() }
func file_Message_proto_init() {
	if File_Message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestHelloMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestResMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Message_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Message_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SharesMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Message_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LCMMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Message_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SKMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Message_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OSVMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Message_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AckMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_Message_proto_goTypes,
		DependencyIndexes: file_Message_proto_depIdxs,
		MessageInfos:      file_Message_proto_msgTypes,
	}.Build()
	File_Message_proto = out.File
	file_Message_proto_rawDesc = nil
	file_Message_proto_goTypes = nil
	file_Message_proto_depIdxs = nil
}
