syntax = "proto3";
package services;

option go_package = ".";

// The node service definition
service NodeService {
  // Node RPC for reconstruction phase
  rpc RBC(ShareMsg) returns (AckMsg) {}
  rpc BroadcastLCM(ShareMsg) returns (AckMsg) {}
  rpc OSV(OSVMessage) returns (AckMsg) {}
}

message Value{
  bytes value = 1;// payload
  bytes validation = 2;// for external validating
}

message Echo{
  bytes sigshare = 1 ;
}

message ShareMsg{
  int64 index = 1;
  repeated bytes zi = 2;
  repeated bytes xi = 3;
}

message AckMsg{}

message OSVMessage{
  int64 fromID = 1;
  int64 destID = 2;
  string mtype = 3;
}