// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.26.1
// source: Message.proto

package protobuf

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	RBCService_Receive_FullMethodName = "/services.RBCService/Receive"
)

// RBCServiceClient is the client API for RBCService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RBCServiceClient interface {
	Receive(ctx context.Context, in *Message, opts ...grpc.CallOption) (*AckMsg, error)
}

type rBCServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRBCServiceClient(cc grpc.ClientConnInterface) RBCServiceClient {
	return &rBCServiceClient{cc}
}

func (c *rBCServiceClient) Receive(ctx context.Context, in *Message, opts ...grpc.CallOption) (*AckMsg, error) {
	out := new(AckMsg)
	err := c.cc.Invoke(ctx, RBCService_Receive_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RBCServiceServer is the server API for RBCService service.
// All implementations must embed UnimplementedRBCServiceServer
// for forward compatibility
type RBCServiceServer interface {
	Receive(context.Context, *Message) (*AckMsg, error)
	mustEmbedUnimplementedRBCServiceServer()
}

// UnimplementedRBCServiceServer must be embedded to have forward compatible implementations.
type UnimplementedRBCServiceServer struct {
}

func (UnimplementedRBCServiceServer) Receive(context.Context, *Message) (*AckMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Receive not implemented")
}
func (UnimplementedRBCServiceServer) mustEmbedUnimplementedRBCServiceServer() {}

// UnsafeRBCServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RBCServiceServer will
// result in compilation errors.
type UnsafeRBCServiceServer interface {
	mustEmbedUnimplementedRBCServiceServer()
}

func RegisterRBCServiceServer(s grpc.ServiceRegistrar, srv RBCServiceServer) {
	s.RegisterService(&RBCService_ServiceDesc, srv)
}

func _RBCService_Receive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RBCServiceServer).Receive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RBCService_Receive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RBCServiceServer).Receive(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

// RBCService_ServiceDesc is the grpc.ServiceDesc for RBCService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RBCService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "services.RBCService",
	HandlerType: (*RBCServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Receive",
			Handler:    _RBCService_Receive_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Message.proto",
}

const (
	ABVSSService_ReceiveShares_FullMethodName = "/services.ABVSSService/ReceiveShares"
	ABVSSService_ReceiveLCM_FullMethodName    = "/services.ABVSSService/ReceiveLCM"
)

// ABVSSServiceClient is the client API for ABVSSService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ABVSSServiceClient interface {
	ReceiveShares(ctx context.Context, in *SharesMessage, opts ...grpc.CallOption) (*AckMsg, error)
	ReceiveLCM(ctx context.Context, in *LCMMessage, opts ...grpc.CallOption) (*AckMsg, error)
}

type aBVSSServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewABVSSServiceClient(cc grpc.ClientConnInterface) ABVSSServiceClient {
	return &aBVSSServiceClient{cc}
}

func (c *aBVSSServiceClient) ReceiveShares(ctx context.Context, in *SharesMessage, opts ...grpc.CallOption) (*AckMsg, error) {
	out := new(AckMsg)
	err := c.cc.Invoke(ctx, ABVSSService_ReceiveShares_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBVSSServiceClient) ReceiveLCM(ctx context.Context, in *LCMMessage, opts ...grpc.CallOption) (*AckMsg, error) {
	out := new(AckMsg)
	err := c.cc.Invoke(ctx, ABVSSService_ReceiveLCM_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ABVSSServiceServer is the server API for ABVSSService service.
// All implementations must embed UnimplementedABVSSServiceServer
// for forward compatibility
type ABVSSServiceServer interface {
	ReceiveShares(context.Context, *SharesMessage) (*AckMsg, error)
	ReceiveLCM(context.Context, *LCMMessage) (*AckMsg, error)
	mustEmbedUnimplementedABVSSServiceServer()
}

// UnimplementedABVSSServiceServer must be embedded to have forward compatible implementations.
type UnimplementedABVSSServiceServer struct {
}

func (UnimplementedABVSSServiceServer) ReceiveShares(context.Context, *SharesMessage) (*AckMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReceiveShares not implemented")
}
func (UnimplementedABVSSServiceServer) ReceiveLCM(context.Context, *LCMMessage) (*AckMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReceiveLCM not implemented")
}
func (UnimplementedABVSSServiceServer) mustEmbedUnimplementedABVSSServiceServer() {}

// UnsafeABVSSServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ABVSSServiceServer will
// result in compilation errors.
type UnsafeABVSSServiceServer interface {
	mustEmbedUnimplementedABVSSServiceServer()
}

func RegisterABVSSServiceServer(s grpc.ServiceRegistrar, srv ABVSSServiceServer) {
	s.RegisterService(&ABVSSService_ServiceDesc, srv)
}

func _ABVSSService_ReceiveShares_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SharesMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABVSSServiceServer).ReceiveShares(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ABVSSService_ReceiveShares_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABVSSServiceServer).ReceiveShares(ctx, req.(*SharesMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABVSSService_ReceiveLCM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LCMMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABVSSServiceServer).ReceiveLCM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ABVSSService_ReceiveLCM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABVSSServiceServer).ReceiveLCM(ctx, req.(*LCMMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// ABVSSService_ServiceDesc is the grpc.ServiceDesc for ABVSSService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ABVSSService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "services.ABVSSService",
	HandlerType: (*ABVSSServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReceiveShares",
			Handler:    _ABVSSService_ReceiveShares_Handler,
		},
		{
			MethodName: "ReceiveLCM",
			Handler:    _ABVSSService_ReceiveLCM_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Message.proto",
}

const (
	OSVService_Receive_FullMethodName = "/services.OSVService/Receive"
)

// OSVServiceClient is the client API for OSVService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OSVServiceClient interface {
	Receive(ctx context.Context, in *OSVMessage, opts ...grpc.CallOption) (*AckMsg, error)
}

type oSVServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOSVServiceClient(cc grpc.ClientConnInterface) OSVServiceClient {
	return &oSVServiceClient{cc}
}

func (c *oSVServiceClient) Receive(ctx context.Context, in *OSVMessage, opts ...grpc.CallOption) (*AckMsg, error) {
	out := new(AckMsg)
	err := c.cc.Invoke(ctx, OSVService_Receive_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OSVServiceServer is the server API for OSVService service.
// All implementations must embed UnimplementedOSVServiceServer
// for forward compatibility
type OSVServiceServer interface {
	Receive(context.Context, *OSVMessage) (*AckMsg, error)
	mustEmbedUnimplementedOSVServiceServer()
}

// UnimplementedOSVServiceServer must be embedded to have forward compatible implementations.
type UnimplementedOSVServiceServer struct {
}

func (UnimplementedOSVServiceServer) Receive(context.Context, *OSVMessage) (*AckMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Receive not implemented")
}
func (UnimplementedOSVServiceServer) mustEmbedUnimplementedOSVServiceServer() {}

// UnsafeOSVServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OSVServiceServer will
// result in compilation errors.
type UnsafeOSVServiceServer interface {
	mustEmbedUnimplementedOSVServiceServer()
}

func RegisterOSVServiceServer(s grpc.ServiceRegistrar, srv OSVServiceServer) {
	s.RegisterService(&OSVService_ServiceDesc, srv)
}

func _OSVService_Receive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OSVMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OSVServiceServer).Receive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OSVService_Receive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OSVServiceServer).Receive(ctx, req.(*OSVMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// OSVService_ServiceDesc is the grpc.ServiceDesc for OSVService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OSVService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "services.OSVService",
	HandlerType: (*OSVServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Receive",
			Handler:    _OSVService_Receive_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Message.proto",
}
