// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v4.25.3
// source: Message.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // instance id
	Id            []byte                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Sender        uint32                 `protobuf:"varint,3,opt,name=sender,proto3" json:"sender,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_Message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Message) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Message) GetSender() uint32 {
	if x != nil {
		return x.Sender
	}
	return 0
}

func (x *Message) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type NewMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Protocol      string                 `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	InstanceID    string                 `protobuf:"bytes,2,opt,name=instanceID,proto3" json:"instanceID,omitempty"`
	FromID        int64                  `protobuf:"varint,3,opt,name=fromID,proto3" json:"fromID,omitempty"`
	DestID        int64                  `protobuf:"varint,4,opt,name=destID,proto3" json:"destID,omitempty"`
	Data          []byte                 `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewMessage) Reset() {
	*x = NewMessage{}
	mi := &file_Message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewMessage) ProtoMessage() {}

func (x *NewMessage) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewMessage.ProtoReflect.Descriptor instead.
func (*NewMessage) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{1}
}

func (x *NewMessage) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *NewMessage) GetInstanceID() string {
	if x != nil {
		return x.InstanceID
	}
	return ""
}

func (x *NewMessage) GetFromID() int64 {
	if x != nil {
		return x.FromID
	}
	return 0
}

func (x *NewMessage) GetDestID() int64 {
	if x != nil {
		return x.DestID
	}
	return 0
}

func (x *NewMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type OptRBCMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgType       int64                  `protobuf:"varint,1,opt,name=msgType,proto3" json:"msgType,omitempty"`
	SessionID     string                 `protobuf:"bytes,2,opt,name=sessionID,proto3" json:"sessionID,omitempty"`
	FromID        int64                  `protobuf:"varint,3,opt,name=fromID,proto3" json:"fromID,omitempty"`
	DestID        int64                  `protobuf:"varint,4,opt,name=destID,proto3" json:"destID,omitempty"`
	Payload       []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptRBCMessage) Reset() {
	*x = OptRBCMessage{}
	mi := &file_Message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptRBCMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptRBCMessage) ProtoMessage() {}

func (x *OptRBCMessage) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptRBCMessage.ProtoReflect.Descriptor instead.
func (*OptRBCMessage) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{2}
}

func (x *OptRBCMessage) GetMsgType() int64 {
	if x != nil {
		return x.MsgType
	}
	return 0
}

func (x *OptRBCMessage) GetSessionID() string {
	if x != nil {
		return x.SessionID
	}
	return ""
}

func (x *OptRBCMessage) GetFromID() int64 {
	if x != nil {
		return x.FromID
	}
	return 0
}

func (x *OptRBCMessage) GetDestID() int64 {
	if x != nil {
		return x.DestID
	}
	return 0
}

func (x *OptRBCMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type OSVMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromID        int64                  `protobuf:"varint,1,opt,name=fromID,proto3" json:"fromID,omitempty"`
	DestID        int64                  `protobuf:"varint,2,opt,name=destID,proto3" json:"destID,omitempty"`
	InstanceID    string                 `protobuf:"bytes,3,opt,name=instanceID,proto3" json:"instanceID,omitempty"`
	MsgType       string                 `protobuf:"bytes,4,opt,name=msgType,proto3" json:"msgType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OSVMessage) Reset() {
	*x = OSVMessage{}
	mi := &file_Message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OSVMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OSVMessage) ProtoMessage() {}

func (x *OSVMessage) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OSVMessage.ProtoReflect.Descriptor instead.
func (*OSVMessage) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{3}
}

func (x *OSVMessage) GetFromID() int64 {
	if x != nil {
		return x.FromID
	}
	return 0
}

func (x *OSVMessage) GetDestID() int64 {
	if x != nil {
		return x.DestID
	}
	return 0
}

func (x *OSVMessage) GetInstanceID() string {
	if x != nil {
		return x.InstanceID
	}
	return ""
}

func (x *OSVMessage) GetMsgType() string {
	if x != nil {
		return x.MsgType
	}
	return ""
}

// modified SS24 protocol message
// 1. ss24 share
type SS24Share struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceID    string                 `protobuf:"bytes,1,opt,name=instanceID,proto3" json:"instanceID,omitempty"`
	Index         int64                  `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	FShare        [][]byte               `protobuf:"bytes,3,rep,name=fShare,proto3" json:"fShare,omitempty"`
	GShare        [][]byte               `protobuf:"bytes,4,rep,name=gShare,proto3" json:"gShare,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SS24Share) Reset() {
	*x = SS24Share{}
	mi := &file_Message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SS24Share) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SS24Share) ProtoMessage() {}

func (x *SS24Share) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SS24Share.ProtoReflect.Descriptor instead.
func (*SS24Share) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{4}
}

func (x *SS24Share) GetInstanceID() string {
	if x != nil {
		return x.InstanceID
	}
	return ""
}

func (x *SS24Share) GetIndex() int64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *SS24Share) GetFShare() [][]byte {
	if x != nil {
		return x.FShare
	}
	return nil
}

func (x *SS24Share) GetGShare() [][]byte {
	if x != nil {
		return x.GShare
	}
	return nil
}

// 2. internal
type ElgamalEncShare struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int64                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	C1            []byte                 `protobuf:"bytes,2,opt,name=c1,proto3" json:"c1,omitempty"`
	C2            []byte                 `protobuf:"bytes,3,opt,name=c2,proto3" json:"c2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ElgamalEncShare) Reset() {
	*x = ElgamalEncShare{}
	mi := &file_Message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ElgamalEncShare) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElgamalEncShare) ProtoMessage() {}

func (x *ElgamalEncShare) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElgamalEncShare.ProtoReflect.Descriptor instead.
func (*ElgamalEncShare) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{5}
}

func (x *ElgamalEncShare) GetIndex() int64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ElgamalEncShare) GetC1() []byte {
	if x != nil {
		return x.C1
	}
	return nil
}

func (x *ElgamalEncShare) GetC2() []byte {
	if x != nil {
		return x.C2
	}
	return nil
}

// 3. internal
type AESEncShare struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int64                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Cipher        []byte                 `protobuf:"bytes,2,opt,name=cipher,proto3" json:"cipher,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AESEncShare) Reset() {
	*x = AESEncShare{}
	mi := &file_Message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AESEncShare) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AESEncShare) ProtoMessage() {}

func (x *AESEncShare) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AESEncShare.ProtoReflect.Descriptor instead.
func (*AESEncShare) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{6}
}

func (x *AESEncShare) GetIndex() int64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *AESEncShare) GetCipher() []byte {
	if x != nil {
		return x.Cipher
	}
	return nil
}

// 4. internal
type AESEncMultiShare struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AesEncShares     []*AESEncShare         `protobuf:"bytes,1,rep,name=aesEncShares,proto3" json:"aesEncShares,omitempty"`
	ElGamalEncShares []*ElgamalEncShare     `protobuf:"bytes,2,rep,name=elGamalEncShares,proto3" json:"elGamalEncShares,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AESEncMultiShare) Reset() {
	*x = AESEncMultiShare{}
	mi := &file_Message_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AESEncMultiShare) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AESEncMultiShare) ProtoMessage() {}

func (x *AESEncMultiShare) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AESEncMultiShare.ProtoReflect.Descriptor instead.
func (*AESEncMultiShare) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{7}
}

func (x *AESEncMultiShare) GetAesEncShares() []*AESEncShare {
	if x != nil {
		return x.AesEncShares
	}
	return nil
}

func (x *AESEncMultiShare) GetElGamalEncShares() []*ElgamalEncShare {
	if x != nil {
		return x.ElGamalEncShares
	}
	return nil
}

// 5. internal
type Poly struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Coefficient   [][]byte               `protobuf:"bytes,1,rep,name=coefficient,proto3" json:"coefficient,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Poly) Reset() {
	*x = Poly{}
	mi := &file_Message_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Poly) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Poly) ProtoMessage() {}

func (x *Poly) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Poly.ProtoReflect.Descriptor instead.
func (*Poly) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{8}
}

func (x *Poly) GetCoefficient() [][]byte {
	if x != nil {
		return x.Coefficient
	}
	return nil
}

// 6. internal
type ChallengePoly struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Polys         []*Poly                `protobuf:"bytes,1,rep,name=polys,proto3" json:"polys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChallengePoly) Reset() {
	*x = ChallengePoly{}
	mi := &file_Message_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChallengePoly) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChallengePoly) ProtoMessage() {}

func (x *ChallengePoly) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChallengePoly.ProtoReflect.Descriptor instead.
func (*ChallengePoly) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{9}
}

func (x *ChallengePoly) GetPolys() []*Poly {
	if x != nil {
		return x.Polys
	}
	return nil
}

// batch DKG protocol message
type DKGMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromID        int64                  `protobuf:"varint,1,opt,name=fromID,proto3" json:"fromID,omitempty"`
	DestID        int64                  `protobuf:"varint,2,opt,name=destID,proto3" json:"destID,omitempty"`
	InstanceID    string                 `protobuf:"bytes,3,opt,name=instanceID,proto3" json:"instanceID,omitempty"`
	Index         int64                  `protobuf:"varint,4,opt,name=index,proto3" json:"index,omitempty"`
	Value         []byte                 `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DKGMessage) Reset() {
	*x = DKGMessage{}
	mi := &file_Message_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DKGMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DKGMessage) ProtoMessage() {}

func (x *DKGMessage) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DKGMessage.ProtoReflect.Descriptor instead.
func (*DKGMessage) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{10}
}

func (x *DKGMessage) GetFromID() int64 {
	if x != nil {
		return x.FromID
	}
	return 0
}

func (x *DKGMessage) GetDestID() int64 {
	if x != nil {
		return x.DestID
	}
	return 0
}

func (x *DKGMessage) GetInstanceID() string {
	if x != nil {
		return x.InstanceID
	}
	return ""
}

func (x *DKGMessage) GetIndex() int64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *DKGMessage) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// internal
type DKGShareMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int64                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Vj            []byte                 `protobuf:"bytes,2,opt,name=vj,proto3" json:"vj,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DKGShareMessage) Reset() {
	*x = DKGShareMessage{}
	mi := &file_Message_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DKGShareMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DKGShareMessage) ProtoMessage() {}

func (x *DKGShareMessage) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DKGShareMessage.ProtoReflect.Descriptor instead.
func (*DKGShareMessage) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{11}
}

func (x *DKGShareMessage) GetIndex() int64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *DKGShareMessage) GetVj() []byte {
	if x != nil {
		return x.Vj
	}
	return nil
}

// opt broadcast message
type DisperseData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MyStripe      []byte                 `protobuf:"bytes,1,opt,name=myStripe,proto3" json:"myStripe,omitempty"`
	SenderStripe  []byte                 `protobuf:"bytes,2,opt,name=senderStripe,proto3" json:"senderStripe,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisperseData) Reset() {
	*x = DisperseData{}
	mi := &file_Message_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisperseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisperseData) ProtoMessage() {}

func (x *DisperseData) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisperseData.ProtoReflect.Descriptor instead.
func (*DisperseData) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{12}
}

func (x *DisperseData) GetMyStripe() []byte {
	if x != nil {
		return x.MyStripe
	}
	return nil
}

func (x *DisperseData) GetSenderStripe() []byte {
	if x != nil {
		return x.SenderStripe
	}
	return nil
}

type BroadcastMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // instance id
	InstanceID    int64                  `protobuf:"varint,2,opt,name=instanceID,proto3" json:"instanceID,omitempty"`
	FromID        int64                  `protobuf:"varint,3,opt,name=fromID,proto3" json:"fromID,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BroadcastMessage) Reset() {
	*x = BroadcastMessage{}
	mi := &file_Message_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastMessage) ProtoMessage() {}

func (x *BroadcastMessage) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastMessage.ProtoReflect.Descriptor instead.
func (*BroadcastMessage) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{13}
}

func (x *BroadcastMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *BroadcastMessage) GetInstanceID() int64 {
	if x != nil {
		return x.InstanceID
	}
	return 0
}

func (x *BroadcastMessage) GetFromID() int64 {
	if x != nil {
		return x.FromID
	}
	return 0
}

func (x *BroadcastMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// harts
// harts protocol message
type HartsMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromID        int64                  `protobuf:"varint,1,opt,name=fromID,proto3" json:"fromID,omitempty"`
	DestID        int64                  `protobuf:"varint,2,opt,name=destID,proto3" json:"destID,omitempty"`
	InstanceID    string                 `protobuf:"bytes,3,opt,name=instanceID,proto3" json:"instanceID,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Value         []byte                 `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HartsMessage) Reset() {
	*x = HartsMessage{}
	mi := &file_Message_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HartsMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HartsMessage) ProtoMessage() {}

func (x *HartsMessage) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HartsMessage.ProtoReflect.Descriptor instead.
func (*HartsMessage) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{14}
}

func (x *HartsMessage) GetFromID() int64 {
	if x != nil {
		return x.FromID
	}
	return 0
}

func (x *HartsMessage) GetDestID() int64 {
	if x != nil {
		return x.DestID
	}
	return 0
}

func (x *HartsMessage) GetInstanceID() string {
	if x != nil {
		return x.InstanceID
	}
	return ""
}

func (x *HartsMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *HartsMessage) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type HartsHavssMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromID        int64                  `protobuf:"varint,1,opt,name=fromID,proto3" json:"fromID,omitempty"`
	DestID        int64                  `protobuf:"varint,2,opt,name=destID,proto3" json:"destID,omitempty"`
	InstanceID    string                 `protobuf:"bytes,3,opt,name=instanceID,proto3" json:"instanceID,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Value         []byte                 `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HartsHavssMessage) Reset() {
	*x = HartsHavssMessage{}
	mi := &file_Message_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HartsHavssMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HartsHavssMessage) ProtoMessage() {}

func (x *HartsHavssMessage) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HartsHavssMessage.ProtoReflect.Descriptor instead.
func (*HartsHavssMessage) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{15}
}

func (x *HartsHavssMessage) GetFromID() int64 {
	if x != nil {
		return x.FromID
	}
	return 0
}

func (x *HartsHavssMessage) GetDestID() int64 {
	if x != nil {
		return x.DestID
	}
	return 0
}

func (x *HartsHavssMessage) GetInstanceID() string {
	if x != nil {
		return x.InstanceID
	}
	return ""
}

func (x *HartsHavssMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *HartsHavssMessage) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// internal: havss commit message
type HartsCommitMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Commit        [][]byte               `protobuf:"bytes,1,rep,name=commit,proto3" json:"commit,omitempty"`
	Si            [][]byte               `protobuf:"bytes,2,rep,name=si,proto3" json:"si,omitempty"`
	Pi            [][]byte               `protobuf:"bytes,3,rep,name=pi,proto3" json:"pi,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HartsCommitMessage) Reset() {
	*x = HartsCommitMessage{}
	mi := &file_Message_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HartsCommitMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HartsCommitMessage) ProtoMessage() {}

func (x *HartsCommitMessage) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HartsCommitMessage.ProtoReflect.Descriptor instead.
func (*HartsCommitMessage) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{16}
}

func (x *HartsCommitMessage) GetCommit() [][]byte {
	if x != nil {
		return x.Commit
	}
	return nil
}

func (x *HartsCommitMessage) GetSi() [][]byte {
	if x != nil {
		return x.Si
	}
	return nil
}

func (x *HartsCommitMessage) GetPi() [][]byte {
	if x != nil {
		return x.Pi
	}
	return nil
}

// internal: inner_product proof
type InnerProductProof struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LVec          [][]byte               `protobuf:"bytes,1,rep,name=lVec,proto3" json:"lVec,omitempty"`
	RVec          [][]byte               `protobuf:"bytes,2,rep,name=rVec,proto3" json:"rVec,omitempty"`
	AVecToSend    [][]byte               `protobuf:"bytes,3,rep,name=aVecToSend,proto3" json:"aVecToSend,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InnerProductProof) Reset() {
	*x = InnerProductProof{}
	mi := &file_Message_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InnerProductProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InnerProductProof) ProtoMessage() {}

func (x *InnerProductProof) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InnerProductProof.ProtoReflect.Descriptor instead.
func (*InnerProductProof) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{17}
}

func (x *InnerProductProof) GetLVec() [][]byte {
	if x != nil {
		return x.LVec
	}
	return nil
}

func (x *InnerProductProof) GetRVec() [][]byte {
	if x != nil {
		return x.RVec
	}
	return nil
}

func (x *InnerProductProof) GetAVecToSend() [][]byte {
	if x != nil {
		return x.AVecToSend
	}
	return nil
}

// internal: nizk inner_product proof in havss
type NizkIPAProof struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             []byte                 `protobuf:"bytes,1,opt,name=A,proto3" json:"A,omitempty"`
	S             []byte                 `protobuf:"bytes,2,opt,name=S,proto3" json:"S,omitempty"`
	T             []byte                 `protobuf:"bytes,3,opt,name=T,proto3" json:"T,omitempty"`
	CVec          [][]byte               `protobuf:"bytes,4,rep,name=cVec,proto3" json:"cVec,omitempty"`
	V             []byte                 `protobuf:"bytes,5,opt,name=v,proto3" json:"v,omitempty"`
	THat          []byte                 `protobuf:"bytes,6,opt,name=tHat,proto3" json:"tHat,omitempty"`
	GExpC         []byte                 `protobuf:"bytes,7,opt,name=gExpC,proto3" json:"gExpC,omitempty"`
	GExpU         []byte                 `protobuf:"bytes,8,opt,name=gExpU,proto3" json:"gExpU,omitempty"`
	IpaProof      *InnerProductProof     `protobuf:"bytes,9,opt,name=ipaProof,proto3" json:"ipaProof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NizkIPAProof) Reset() {
	*x = NizkIPAProof{}
	mi := &file_Message_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NizkIPAProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NizkIPAProof) ProtoMessage() {}

func (x *NizkIPAProof) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NizkIPAProof.ProtoReflect.Descriptor instead.
func (*NizkIPAProof) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{18}
}

func (x *NizkIPAProof) GetA() []byte {
	if x != nil {
		return x.A
	}
	return nil
}

func (x *NizkIPAProof) GetS() []byte {
	if x != nil {
		return x.S
	}
	return nil
}

func (x *NizkIPAProof) GetT() []byte {
	if x != nil {
		return x.T
	}
	return nil
}

func (x *NizkIPAProof) GetCVec() [][]byte {
	if x != nil {
		return x.CVec
	}
	return nil
}

func (x *NizkIPAProof) GetV() []byte {
	if x != nil {
		return x.V
	}
	return nil
}

func (x *NizkIPAProof) GetTHat() []byte {
	if x != nil {
		return x.THat
	}
	return nil
}

func (x *NizkIPAProof) GetGExpC() []byte {
	if x != nil {
		return x.GExpC
	}
	return nil
}

func (x *NizkIPAProof) GetGExpU() []byte {
	if x != nil {
		return x.GExpU
	}
	return nil
}

func (x *NizkIPAProof) GetIpaProof() *InnerProductProof {
	if x != nil {
		return x.IpaProof
	}
	return nil
}

// internal: havss row message
type HartsRowVectorMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CI            [][]byte               `protobuf:"bytes,1,rep,name=c_i,json=cI,proto3" json:"c_i,omitempty"`
	PiI           []*NizkIPAProof        `protobuf:"bytes,2,rep,name=pi_i,json=piI,proto3" json:"pi_i,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HartsRowVectorMessage) Reset() {
	*x = HartsRowVectorMessage{}
	mi := &file_Message_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HartsRowVectorMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HartsRowVectorMessage) ProtoMessage() {}

func (x *HartsRowVectorMessage) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HartsRowVectorMessage.ProtoReflect.Descriptor instead.
func (*HartsRowVectorMessage) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{19}
}

func (x *HartsRowVectorMessage) GetCI() [][]byte {
	if x != nil {
		return x.CI
	}
	return nil
}

func (x *HartsRowVectorMessage) GetPiI() []*NizkIPAProof {
	if x != nil {
		return x.PiI
	}
	return nil
}

// internal: havss column
type HartsColumnMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CIj           []byte                 `protobuf:"bytes,1,opt,name=c_ij,json=cIj,proto3" json:"c_ij,omitempty"`
	PIj           *NizkIPAProof          `protobuf:"bytes,2,opt,name=p_ij,json=pIj,proto3" json:"p_ij,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HartsColumnMessage) Reset() {
	*x = HartsColumnMessage{}
	mi := &file_Message_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HartsColumnMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HartsColumnMessage) ProtoMessage() {}

func (x *HartsColumnMessage) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HartsColumnMessage.ProtoReflect.Descriptor instead.
func (*HartsColumnMessage) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{20}
}

func (x *HartsColumnMessage) GetCIj() []byte {
	if x != nil {
		return x.CIj
	}
	return nil
}

func (x *HartsColumnMessage) GetPIj() *NizkIPAProof {
	if x != nil {
		return x.PIj
	}
	return nil
}

// internal: signature in harts
type HartsProposeSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         []int64                `protobuf:"varint,1,rep,packed,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HartsProposeSet) Reset() {
	*x = HartsProposeSet{}
	mi := &file_Message_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HartsProposeSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HartsProposeSet) ProtoMessage() {}

func (x *HartsProposeSet) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HartsProposeSet.ProtoReflect.Descriptor instead.
func (*HartsProposeSet) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{21}
}

func (x *HartsProposeSet) GetIndex() []int64 {
	if x != nil {
		return x.Index
	}
	return nil
}

// validated aba protocol message
// sub protocol: reliable agreement
type RAMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromID        int64                  `protobuf:"varint,1,opt,name=fromID,proto3" json:"fromID,omitempty"`
	DestID        int64                  `protobuf:"varint,2,opt,name=destID,proto3" json:"destID,omitempty"`
	InstanceID    string                 `protobuf:"bytes,3,opt,name=instanceID,proto3" json:"instanceID,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Value         []byte                 `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RAMessage) Reset() {
	*x = RAMessage{}
	mi := &file_Message_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RAMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RAMessage) ProtoMessage() {}

func (x *RAMessage) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RAMessage.ProtoReflect.Descriptor instead.
func (*RAMessage) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{22}
}

func (x *RAMessage) GetFromID() int64 {
	if x != nil {
		return x.FromID
	}
	return 0
}

func (x *RAMessage) GetDestID() int64 {
	if x != nil {
		return x.DestID
	}
	return 0
}

func (x *RAMessage) GetInstanceID() string {
	if x != nil {
		return x.InstanceID
	}
	return ""
}

func (x *RAMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RAMessage) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// sub protocol: Asynchronous Secret Key Sharing protocol message
type ASKSMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromID        int64                  `protobuf:"varint,1,opt,name=fromID,proto3" json:"fromID,omitempty"`
	DestID        int64                  `protobuf:"varint,2,opt,name=destID,proto3" json:"destID,omitempty"`
	InstanceID    string                 `protobuf:"bytes,3,opt,name=instanceID,proto3" json:"instanceID,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Value         []byte                 `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ASKSMessage) Reset() {
	*x = ASKSMessage{}
	mi := &file_Message_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ASKSMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ASKSMessage) ProtoMessage() {}

func (x *ASKSMessage) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ASKSMessage.ProtoReflect.Descriptor instead.
func (*ASKSMessage) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{23}
}

func (x *ASKSMessage) GetFromID() int64 {
	if x != nil {
		return x.FromID
	}
	return 0
}

func (x *ASKSMessage) GetDestID() int64 {
	if x != nil {
		return x.DestID
	}
	return 0
}

func (x *ASKSMessage) GetInstanceID() string {
	if x != nil {
		return x.InstanceID
	}
	return ""
}

func (x *ASKSMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ASKSMessage) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// sub protocol: internal ASKS hash vector
type ASKSHashVector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HashByte      [][]byte               `protobuf:"bytes,1,rep,name=hashByte,proto3" json:"hashByte,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ASKSHashVector) Reset() {
	*x = ASKSHashVector{}
	mi := &file_Message_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ASKSHashVector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ASKSHashVector) ProtoMessage() {}

func (x *ASKSHashVector) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ASKSHashVector.ProtoReflect.Descriptor instead.
func (*ASKSHashVector) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{24}
}

func (x *ASKSHashVector) GetHashByte() [][]byte {
	if x != nil {
		return x.HashByte
	}
	return nil
}

// sub protocol: Index Gather protocol message
type IGMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromID        int64                  `protobuf:"varint,1,opt,name=fromID,proto3" json:"fromID,omitempty"`
	DestID        int64                  `protobuf:"varint,2,opt,name=DestID,proto3" json:"DestID,omitempty"`
	InstanceID    string                 `protobuf:"bytes,3,opt,name=instanceID,proto3" json:"instanceID,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Set           []int64                `protobuf:"varint,5,rep,packed,name=set,proto3" json:"set,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IGMessage) Reset() {
	*x = IGMessage{}
	mi := &file_Message_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IGMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IGMessage) ProtoMessage() {}

func (x *IGMessage) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IGMessage.ProtoReflect.Descriptor instead.
func (*IGMessage) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{25}
}

func (x *IGMessage) GetFromID() int64 {
	if x != nil {
		return x.FromID
	}
	return 0
}

func (x *IGMessage) GetDestID() int64 {
	if x != nil {
		return x.DestID
	}
	return 0
}

func (x *IGMessage) GetInstanceID() string {
	if x != nil {
		return x.InstanceID
	}
	return ""
}

func (x *IGMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *IGMessage) GetSet() []int64 {
	if x != nil {
		return x.Set
	}
	return nil
}

// sub protocol: Index Cover Gather protocol message
type ICGMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromID        int64                  `protobuf:"varint,1,opt,name=fromID,proto3" json:"fromID,omitempty"`
	DestID        int64                  `protobuf:"varint,2,opt,name=DestID,proto3" json:"DestID,omitempty"`
	InstanceID    string                 `protobuf:"bytes,3,opt,name=instanceID,proto3" json:"instanceID,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ICGMessage) Reset() {
	*x = ICGMessage{}
	mi := &file_Message_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ICGMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ICGMessage) ProtoMessage() {}

func (x *ICGMessage) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ICGMessage.ProtoReflect.Descriptor instead.
func (*ICGMessage) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{26}
}

func (x *ICGMessage) GetFromID() int64 {
	if x != nil {
		return x.FromID
	}
	return 0
}

func (x *ICGMessage) GetDestID() int64 {
	if x != nil {
		return x.DestID
	}
	return 0
}

func (x *ICGMessage) GetInstanceID() string {
	if x != nil {
		return x.InstanceID
	}
	return ""
}

func (x *ICGMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

// internal: rbc on pre_i in vaba
type PreIRBCMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pi            []int64                `protobuf:"varint,2,rep,packed,name=Pi,proto3" json:"Pi,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreIRBCMessage) Reset() {
	*x = PreIRBCMessage{}
	mi := &file_Message_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreIRBCMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreIRBCMessage) ProtoMessage() {}

func (x *PreIRBCMessage) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreIRBCMessage.ProtoReflect.Descriptor instead.
func (*PreIRBCMessage) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{27}
}

func (x *PreIRBCMessage) GetPi() []int64 {
	if x != nil {
		return x.Pi
	}
	return nil
}

// provable broadcast
type Value struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`           // paload
	Validation    []byte                 `protobuf:"bytes,2,opt,name=validation,proto3" json:"validation,omitempty"` // for external validating
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_Message_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{28}
}

func (x *Value) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Value) GetValidation() []byte {
	if x != nil {
		return x.Validation
	}
	return nil
}

type Echo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sigshare      []byte                 `protobuf:"bytes,1,opt,name=sigshare,proto3" json:"sigshare,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Echo) Reset() {
	*x = Echo{}
	mi := &file_Message_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Echo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Echo) ProtoMessage() {}

func (x *Echo) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Echo.ProtoReflect.Descriptor instead.
func (*Echo) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{29}
}

func (x *Echo) GetSigshare() []byte {
	if x != nil {
		return x.Sigshare
	}
	return nil
}

// smvba
type Lock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Sig           []byte                 `protobuf:"bytes,2,opt,name=sig,proto3" json:"sig,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Lock) Reset() {
	*x = Lock{}
	mi := &file_Message_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Lock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lock) ProtoMessage() {}

func (x *Lock) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lock.ProtoReflect.Descriptor instead.
func (*Lock) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{30}
}

func (x *Lock) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Lock) GetSig() []byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

type Finish struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Sig           []byte                 `protobuf:"bytes,2,opt,name=sig,proto3" json:"sig,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Finish) Reset() {
	*x = Finish{}
	mi := &file_Message_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Finish) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Finish) ProtoMessage() {}

func (x *Finish) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Finish.ProtoReflect.Descriptor instead.
func (*Finish) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{31}
}

func (x *Finish) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Finish) GetSig() []byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

type Done struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CoinShare     []byte                 `protobuf:"bytes,1,opt,name=coinShare,proto3" json:"coinShare,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Done) Reset() {
	*x = Done{}
	mi := &file_Message_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Done) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Done) ProtoMessage() {}

func (x *Done) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Done.ProtoReflect.Descriptor instead.
func (*Done) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{32}
}

func (x *Done) GetCoinShare() []byte {
	if x != nil {
		return x.CoinShare
	}
	return nil
}

type Halt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Sig           []byte                 `protobuf:"bytes,2,opt,name=sig,proto3" json:"sig,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Halt) Reset() {
	*x = Halt{}
	mi := &file_Message_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Halt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Halt) ProtoMessage() {}

func (x *Halt) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Halt.ProtoReflect.Descriptor instead.
func (*Halt) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{33}
}

func (x *Halt) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Halt) GetSig() []byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

type PreVote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vote          bool                   `protobuf:"varint,1,opt,name=vote,proto3" json:"vote,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Sig           []byte                 `protobuf:"bytes,3,opt,name=sig,proto3" json:"sig,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreVote) Reset() {
	*x = PreVote{}
	mi := &file_Message_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreVote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreVote) ProtoMessage() {}

func (x *PreVote) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreVote.ProtoReflect.Descriptor instead.
func (*PreVote) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{34}
}

func (x *PreVote) GetVote() bool {
	if x != nil {
		return x.Vote
	}
	return false
}

func (x *PreVote) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *PreVote) GetSig() []byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

type Vote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vote          bool                   `protobuf:"varint,1,opt,name=vote,proto3" json:"vote,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Sig           []byte                 `protobuf:"bytes,3,opt,name=sig,proto3" json:"sig,omitempty"`
	Sigshare      []byte                 `protobuf:"bytes,4,opt,name=sigshare,proto3" json:"sigshare,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vote) Reset() {
	*x = Vote{}
	mi := &file_Message_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vote) ProtoMessage() {}

func (x *Vote) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vote.ProtoReflect.Descriptor instead.
func (*Vote) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{35}
}

func (x *Vote) GetVote() bool {
	if x != nil {
		return x.Vote
	}
	return false
}

func (x *Vote) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Vote) GetSig() []byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

func (x *Vote) GetSigshare() []byte {
	if x != nil {
		return x.Sigshare
	}
	return nil
}

//sDumbo
type Proposal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tx            []byte                 `protobuf:"bytes,1,opt,name=tx,proto3" json:"tx,omitempty"`
	View          []uint32               `protobuf:"varint,2,rep,packed,name=view,proto3" json:"view,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Proposal) Reset() {
	*x = Proposal{}
	mi := &file_Message_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Proposal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Proposal) ProtoMessage() {}

func (x *Proposal) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Proposal.ProtoReflect.Descriptor instead.
func (*Proposal) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{36}
}

func (x *Proposal) GetTx() []byte {
	if x != nil {
		return x.Tx
	}
	return nil
}

func (x *Proposal) GetView() []uint32 {
	if x != nil {
		return x.View
	}
	return nil
}

type BLock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          []byte                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Sig           []byte                 `protobuf:"bytes,2,opt,name=sig,proto3" json:"sig,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BLock) Reset() {
	*x = BLock{}
	mi := &file_Message_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BLock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BLock) ProtoMessage() {}

func (x *BLock) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BLock.ProtoReflect.Descriptor instead.
func (*BLock) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{37}
}

func (x *BLock) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *BLock) GetSig() []byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

type BLockSetValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           []uint32               `protobuf:"varint,1,rep,packed,name=pid,proto3" json:"pid,omitempty"`
	Hash          [][]byte               `protobuf:"bytes,2,rep,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BLockSetValue) Reset() {
	*x = BLockSetValue{}
	mi := &file_Message_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BLockSetValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BLockSetValue) ProtoMessage() {}

func (x *BLockSetValue) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BLockSetValue.ProtoReflect.Descriptor instead.
func (*BLockSetValue) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{38}
}

func (x *BLockSetValue) GetPid() []uint32 {
	if x != nil {
		return x.Pid
	}
	return nil
}

func (x *BLockSetValue) GetHash() [][]byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

type BLockSetValidation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sig           [][]byte               `protobuf:"bytes,1,rep,name=sig,proto3" json:"sig,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BLockSetValidation) Reset() {
	*x = BLockSetValidation{}
	mi := &file_Message_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BLockSetValidation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BLockSetValidation) ProtoMessage() {}

func (x *BLockSetValidation) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BLockSetValidation.ProtoReflect.Descriptor instead.
func (*BLockSetValidation) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{39}
}

func (x *BLockSetValidation) GetSig() [][]byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

type Call struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Indices       []uint32               `protobuf:"varint,1,rep,packed,name=indices,proto3" json:"indices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Call) Reset() {
	*x = Call{}
	mi := &file_Message_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Call) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Call) ProtoMessage() {}

func (x *Call) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Call.ProtoReflect.Descriptor instead.
func (*Call) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{40}
}

func (x *Call) GetIndices() []uint32 {
	if x != nil {
		return x.Indices
	}
	return nil
}

type Help struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Indices       []uint32               `protobuf:"varint,1,rep,packed,name=indices,proto3" json:"indices,omitempty"`
	ShardAndProof []*Help_ShardAndProof  `protobuf:"bytes,2,rep,name=shardAndProof,proto3" json:"shardAndProof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Help) Reset() {
	*x = Help{}
	mi := &file_Message_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Help) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Help) ProtoMessage() {}

func (x *Help) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Help.ProtoReflect.Descriptor instead.
func (*Help) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{41}
}

func (x *Help) GetIndices() []uint32 {
	if x != nil {
		return x.Indices
	}
	return nil
}

func (x *Help) GetShardAndProof() []*Help_ShardAndProof {
	if x != nil {
		return x.ShardAndProof
	}
	return nil
}

//TSE
type Dec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DecShare      []byte                 `protobuf:"bytes,2,opt,name=decShare,proto3" json:"decShare,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dec) Reset() {
	*x = Dec{}
	mi := &file_Message_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dec) ProtoMessage() {}

func (x *Dec) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dec.ProtoReflect.Descriptor instead.
func (*Dec) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{42}
}

func (x *Dec) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Dec) GetDecShare() []byte {
	if x != nil {
		return x.DecShare
	}
	return nil
}

type Help_ShardAndProof struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vc            []byte                 `protobuf:"bytes,1,opt,name=vc,proto3" json:"vc,omitempty"`
	Shard         []byte                 `protobuf:"bytes,2,opt,name=shard,proto3" json:"shard,omitempty"`
	Proof1        [][]byte               `protobuf:"bytes,3,rep,name=proof1,proto3" json:"proof1,omitempty"`
	Proof2        []int64                `protobuf:"varint,4,rep,packed,name=proof2,proto3" json:"proof2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Help_ShardAndProof) Reset() {
	*x = Help_ShardAndProof{}
	mi := &file_Message_proto_msgTypes[43]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Help_ShardAndProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Help_ShardAndProof) ProtoMessage() {}

func (x *Help_ShardAndProof) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[43]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Help_ShardAndProof.ProtoReflect.Descriptor instead.
func (*Help_ShardAndProof) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{41, 0}
}

func (x *Help_ShardAndProof) GetVc() []byte {
	if x != nil {
		return x.Vc
	}
	return nil
}

func (x *Help_ShardAndProof) GetShard() []byte {
	if x != nil {
		return x.Shard
	}
	return nil
}

func (x *Help_ShardAndProof) GetProof1() [][]byte {
	if x != nil {
		return x.Proof1
	}
	return nil
}

func (x *Help_ShardAndProof) GetProof2() []int64 {
	if x != nil {
		return x.Proof2
	}
	return nil
}

var File_Message_proto protoreflect.FileDescriptor

var file_Message_proto_rawDesc = string([]byte{
	0x0a, 0x0d, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x59, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06,
	0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x8c, 0x01, 0x0a, 0x0a, 0x4e,
	0x65, 0x77, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63,
	0x65, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x69, 0x6e, 0x73, 0x74, 0x61,
	0x6e, 0x63, 0x65, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x72, 0x6f, 0x6d, 0x49, 0x44, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x66, 0x72, 0x6f, 0x6d, 0x49, 0x44, 0x12, 0x16, 0x0a,
	0x06, 0x64, 0x65, 0x73, 0x74, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x64,
	0x65, 0x73, 0x74, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x91, 0x01, 0x0a, 0x0d, 0x4f, 0x70,
	0x74, 0x52, 0x42, 0x43, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x6d, 0x73,
	0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x72, 0x6f, 0x6d, 0x49, 0x44, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x66, 0x72, 0x6f, 0x6d, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x64,
	0x65, 0x73, 0x74, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x64, 0x65, 0x73,
	0x74, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x76, 0x0a,
	0x0a, 0x4f, 0x53, 0x56, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x66,
	0x72, 0x6f, 0x6d, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x66, 0x72, 0x6f,
	0x6d, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x73, 0x74, 0x49, 0x44, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x64, 0x65, 0x73, 0x74, 0x49, 0x44, 0x12, 0x1e, 0x0a, 0x0a, 0x69,
	0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x73,
	0x67, 0x54, 0x79, 0x70, 0x65, 0x22, 0x71, 0x0a, 0x09, 0x53, 0x53, 0x32, 0x34, 0x53, 0x68, 0x61,
	0x72, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65,
	0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x53, 0x68, 0x61,
	0x72, 0x65, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x06, 0x66, 0x53, 0x68, 0x61, 0x72, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x67, 0x53, 0x68, 0x61, 0x72, 0x65, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0c,
	0x52, 0x06, 0x67, 0x53, 0x68, 0x61, 0x72, 0x65, 0x22, 0x47, 0x0a, 0x0f, 0x45, 0x6c, 0x67, 0x61,
	0x6d, 0x61, 0x6c, 0x45, 0x6e, 0x63, 0x53, 0x68, 0x61, 0x72, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x69,
	0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65,
	0x78, 0x12, 0x0e, 0x0a, 0x02, 0x63, 0x31, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x63,
	0x31, 0x12, 0x0e, 0x0a, 0x02, 0x63, 0x32, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x63,
	0x32, 0x22, 0x3b, 0x0a, 0x0b, 0x41, 0x45, 0x53, 0x45, 0x6e, 0x63, 0x53, 0x68, 0x61, 0x72, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x69, 0x70, 0x68, 0x65, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x63, 0x69, 0x70, 0x68, 0x65, 0x72, 0x22, 0x82,
	0x01, 0x0a, 0x10, 0x41, 0x45, 0x53, 0x45, 0x6e, 0x63, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x53, 0x68,
	0x61, 0x72, 0x65, 0x12, 0x30, 0x0a, 0x0c, 0x61, 0x65, 0x73, 0x45, 0x6e, 0x63, 0x53, 0x68, 0x61,
	0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x41, 0x45, 0x53, 0x45,
	0x6e, 0x63, 0x53, 0x68, 0x61, 0x72, 0x65, 0x52, 0x0c, 0x61, 0x65, 0x73, 0x45, 0x6e, 0x63, 0x53,
	0x68, 0x61, 0x72, 0x65, 0x73, 0x12, 0x3c, 0x0a, 0x10, 0x65, 0x6c, 0x47, 0x61, 0x6d, 0x61, 0x6c,
	0x45, 0x6e, 0x63, 0x53, 0x68, 0x61, 0x72, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x45, 0x6c, 0x67, 0x61, 0x6d, 0x61, 0x6c, 0x45, 0x6e, 0x63, 0x53, 0x68, 0x61, 0x72,
	0x65, 0x52, 0x10, 0x65, 0x6c, 0x47, 0x61, 0x6d, 0x61, 0x6c, 0x45, 0x6e, 0x63, 0x53, 0x68, 0x61,
	0x72, 0x65, 0x73, 0x22, 0x28, 0x0a, 0x04, 0x70, 0x6f, 0x6c, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x63,
	0x6f, 0x65, 0x66, 0x66, 0x69, 0x63, 0x69, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c,
	0x52, 0x0b, 0x63, 0x6f, 0x65, 0x66, 0x66, 0x69, 0x63, 0x69, 0x65, 0x6e, 0x74, 0x22, 0x2c, 0x0a,
	0x0d, 0x63, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x50, 0x6f, 0x6c, 0x79, 0x12, 0x1b,
	0x0a, 0x05, 0x70, 0x6f, 0x6c, 0x79, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x05, 0x2e,
	0x70, 0x6f, 0x6c, 0x79, 0x52, 0x05, 0x70, 0x6f, 0x6c, 0x79, 0x73, 0x22, 0x88, 0x01, 0x0a, 0x0a,
	0x44, 0x4b, 0x47, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x72,
	0x6f, 0x6d, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x66, 0x72, 0x6f, 0x6d,
	0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x73, 0x74, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x64, 0x65, 0x73, 0x74, 0x49, 0x44, 0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x6e,
	0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e,
	0x64, 0x65, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x37, 0x0a, 0x0f, 0x44, 0x4b, 0x47, 0x53, 0x68, 0x61,
	0x72, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64,
	0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12,
	0x0e, 0x0a, 0x02, 0x76, 0x6a, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x76, 0x6a, 0x22,
	0x4e, 0x0a, 0x0c, 0x44, 0x69, 0x73, 0x70, 0x65, 0x72, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x1a, 0x0a, 0x08, 0x6d, 0x79, 0x53, 0x74, 0x72, 0x69, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x08, 0x6d, 0x79, 0x53, 0x74, 0x72, 0x69, 0x70, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x73,
	0x65, 0x6e, 0x64, 0x65, 0x72, 0x53, 0x74, 0x72, 0x69, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x0c, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x53, 0x74, 0x72, 0x69, 0x70, 0x65, 0x22,
	0x72, 0x0a, 0x10, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x6e, 0x73, 0x74, 0x61,
	0x6e, 0x63, 0x65, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x69, 0x6e, 0x73,
	0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x72, 0x6f, 0x6d, 0x49,
	0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x66, 0x72, 0x6f, 0x6d, 0x49, 0x44, 0x12,
	0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x22, 0x88, 0x01, 0x0a, 0x0c, 0x48, 0x61, 0x72, 0x74, 0x73, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x72, 0x6f, 0x6d, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x66, 0x72, 0x6f, 0x6d, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06,
	0x64, 0x65, 0x73, 0x74, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x64, 0x65,
	0x73, 0x74, 0x49, 0x44, 0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65,
	0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e,
	0x63, 0x65, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x8d,
	0x01, 0x0a, 0x11, 0x48, 0x61, 0x72, 0x74, 0x73, 0x48, 0x61, 0x76, 0x73, 0x73, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x72, 0x6f, 0x6d, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x66, 0x72, 0x6f, 0x6d, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06,
	0x64, 0x65, 0x73, 0x74, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x64, 0x65,
	0x73, 0x74, 0x49, 0x44, 0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65,
	0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e,
	0x63, 0x65, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x4c,
	0x0a, 0x12, 0x48, 0x61, 0x72, 0x74, 0x73, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0c, 0x52, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x73, 0x69, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x02, 0x73, 0x69, 0x12, 0x0e, 0x0a, 0x02,
	0x70, 0x69, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x02, 0x70, 0x69, 0x22, 0x5b, 0x0a, 0x11,
	0x49, 0x6e, 0x6e, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x50, 0x72, 0x6f, 0x6f,
	0x66, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x56, 0x65, 0x63, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52,
	0x04, 0x6c, 0x56, 0x65, 0x63, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x56, 0x65, 0x63, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0c, 0x52, 0x04, 0x72, 0x56, 0x65, 0x63, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x56, 0x65,
	0x63, 0x54, 0x6f, 0x53, 0x65, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x0a, 0x61,
	0x56, 0x65, 0x63, 0x54, 0x6f, 0x53, 0x65, 0x6e, 0x64, 0x22, 0xca, 0x01, 0x0a, 0x0c, 0x4e, 0x69,
	0x7a, 0x6b, 0x49, 0x50, 0x41, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x12, 0x0c, 0x0a, 0x01, 0x41, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x01, 0x41, 0x12, 0x0c, 0x0a, 0x01, 0x53, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x01, 0x53, 0x12, 0x0c, 0x0a, 0x01, 0x54, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x01, 0x54, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x56, 0x65, 0x63, 0x18, 0x04, 0x20, 0x03,
	0x28, 0x0c, 0x52, 0x04, 0x63, 0x56, 0x65, 0x63, 0x12, 0x0c, 0x0a, 0x01, 0x76, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x01, 0x76, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x48, 0x61, 0x74, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x74, 0x48, 0x61, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x45,
	0x78, 0x70, 0x43, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x67, 0x45, 0x78, 0x70, 0x43,
	0x12, 0x14, 0x0a, 0x05, 0x67, 0x45, 0x78, 0x70, 0x55, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x05, 0x67, 0x45, 0x78, 0x70, 0x55, 0x12, 0x2e, 0x0a, 0x08, 0x69, 0x70, 0x61, 0x50, 0x72, 0x6f,
	0x6f, 0x66, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x49, 0x6e, 0x6e, 0x65, 0x72,
	0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x52, 0x08, 0x69, 0x70,
	0x61, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x22, 0x4a, 0x0a, 0x15, 0x48, 0x61, 0x72, 0x74, 0x73, 0x52,
	0x6f, 0x77, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x0f, 0x0a, 0x03, 0x63, 0x5f, 0x69, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x02, 0x63, 0x49,
	0x12, 0x20, 0x0a, 0x04, 0x70, 0x69, 0x5f, 0x69, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d,
	0x2e, 0x4e, 0x69, 0x7a, 0x6b, 0x49, 0x50, 0x41, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x52, 0x03, 0x70,
	0x69, 0x49, 0x22, 0x49, 0x0a, 0x12, 0x48, 0x61, 0x72, 0x74, 0x73, 0x43, 0x6f, 0x6c, 0x75, 0x6d,
	0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x11, 0x0a, 0x04, 0x63, 0x5f, 0x69, 0x6a,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x63, 0x49, 0x6a, 0x12, 0x20, 0x0a, 0x04, 0x70,
	0x5f, 0x69, 0x6a, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x4e, 0x69, 0x7a, 0x6b,
	0x49, 0x50, 0x41, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x52, 0x03, 0x70, 0x49, 0x6a, 0x22, 0x27, 0x0a,
	0x0f, 0x48, 0x61, 0x72, 0x74, 0x73, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x65, 0x53, 0x65, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52,
	0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x22, 0x85, 0x01, 0x0a, 0x09, 0x52, 0x41, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x72, 0x6f, 0x6d, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x66, 0x72, 0x6f, 0x6d, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06,
	0x64, 0x65, 0x73, 0x74, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x64, 0x65,
	0x73, 0x74, 0x49, 0x44, 0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65,
	0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e,
	0x63, 0x65, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x87,
	0x01, 0x0a, 0x0b, 0x41, 0x53, 0x4b, 0x53, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x66, 0x72, 0x6f, 0x6d, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x66, 0x72, 0x6f, 0x6d, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x73, 0x74, 0x49, 0x44,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x64, 0x65, 0x73, 0x74, 0x49, 0x44, 0x12, 0x1e,
	0x0a, 0x0a, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x44, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x2c, 0x0a, 0x0e, 0x41, 0x53, 0x4b, 0x53,
	0x48, 0x61, 0x73, 0x68, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x61,
	0x73, 0x68, 0x42, 0x79, 0x74, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x08, 0x68, 0x61,
	0x73, 0x68, 0x42, 0x79, 0x74, 0x65, 0x22, 0x81, 0x01, 0x0a, 0x09, 0x49, 0x47, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x72, 0x6f, 0x6d, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x66, 0x72, 0x6f, 0x6d, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06,
	0x44, 0x65, 0x73, 0x74, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x44, 0x65,
	0x73, 0x74, 0x49, 0x44, 0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65,
	0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e,
	0x63, 0x65, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x74, 0x18,
	0x05, 0x20, 0x03, 0x28, 0x03, 0x52, 0x03, 0x73, 0x65, 0x74, 0x22, 0x70, 0x0a, 0x0a, 0x49, 0x43,
	0x47, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x72, 0x6f, 0x6d,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x66, 0x72, 0x6f, 0x6d, 0x49, 0x44,
	0x12, 0x16, 0x0a, 0x06, 0x44, 0x65, 0x73, 0x74, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x44, 0x65, 0x73, 0x74, 0x49, 0x44, 0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x6e, 0x73, 0x74,
	0x61, 0x6e, 0x63, 0x65, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x69, 0x6e,
	0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x20, 0x0a, 0x0e,
	0x50, 0x72, 0x65, 0x49, 0x52, 0x42, 0x43, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x50, 0x69, 0x18, 0x02, 0x20, 0x03, 0x28, 0x03, 0x52, 0x02, 0x50, 0x69, 0x22, 0x3d,
	0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1e, 0x0a,
	0x0a, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x0a, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x22, 0x0a,
	0x04, 0x45, 0x63, 0x68, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x69, 0x67, 0x73, 0x68, 0x61, 0x72,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x73, 0x69, 0x67, 0x73, 0x68, 0x61, 0x72,
	0x65, 0x22, 0x2e, 0x0a, 0x04, 0x4c, 0x6f, 0x63, 0x6b, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x73, 0x69, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x73, 0x69,
	0x67, 0x22, 0x30, 0x0a, 0x06, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x69, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03,
	0x73, 0x69, 0x67, 0x22, 0x24, 0x0a, 0x04, 0x44, 0x6f, 0x6e, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x63,
	0x6f, 0x69, 0x6e, 0x53, 0x68, 0x61, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09,
	0x63, 0x6f, 0x69, 0x6e, 0x53, 0x68, 0x61, 0x72, 0x65, 0x22, 0x2e, 0x0a, 0x04, 0x48, 0x61, 0x6c,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x69, 0x67, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x73, 0x69, 0x67, 0x22, 0x45, 0x0a, 0x07, 0x50, 0x72, 0x65,
	0x56, 0x6f, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x76, 0x6f, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x04, 0x76, 0x6f, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x73, 0x69, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x73, 0x69, 0x67,
	0x22, 0x5e, 0x0a, 0x04, 0x56, 0x6f, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x76, 0x6f, 0x74, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x76, 0x6f, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x69, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x03, 0x73, 0x69, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x69, 0x67, 0x73, 0x68, 0x61, 0x72, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x73, 0x69, 0x67, 0x73, 0x68, 0x61, 0x72, 0x65,
	0x22, 0x2e, 0x0a, 0x08, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61, 0x6c, 0x12, 0x0e, 0x0a, 0x02,
	0x74, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x74, 0x78, 0x12, 0x12, 0x0a, 0x04,
	0x76, 0x69, 0x65, 0x77, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x04, 0x76, 0x69, 0x65, 0x77,
	0x22, 0x2d, 0x0a, 0x05, 0x42, 0x4c, 0x6f, 0x63, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73,
	0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x12, 0x10, 0x0a,
	0x03, 0x73, 0x69, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x73, 0x69, 0x67, 0x22,
	0x35, 0x0a, 0x0d, 0x42, 0x4c, 0x6f, 0x63, 0x6b, 0x53, 0x65, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x70, 0x69, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x03, 0x70,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0c,
	0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x22, 0x26, 0x0a, 0x12, 0x42, 0x4c, 0x6f, 0x63, 0x6b, 0x53,
	0x65, 0x74, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03,
	0x73, 0x69, 0x67, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x03, 0x73, 0x69, 0x67, 0x22, 0x20,
	0x0a, 0x04, 0x43, 0x61, 0x6c, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x6e, 0x64, 0x69, 0x63, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x07, 0x69, 0x6e, 0x64, 0x69, 0x63, 0x65, 0x73,
	0x22, 0xc2, 0x01, 0x0a, 0x04, 0x48, 0x65, 0x6c, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x6e, 0x64,
	0x69, 0x63, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x07, 0x69, 0x6e, 0x64, 0x69,
	0x63, 0x65, 0x73, 0x12, 0x39, 0x0a, 0x0d, 0x73, 0x68, 0x61, 0x72, 0x64, 0x41, 0x6e, 0x64, 0x50,
	0x72, 0x6f, 0x6f, 0x66, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x48, 0x65, 0x6c,
	0x70, 0x2e, 0x53, 0x68, 0x61, 0x72, 0x64, 0x41, 0x6e, 0x64, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x52,
	0x0d, 0x73, 0x68, 0x61, 0x72, 0x64, 0x41, 0x6e, 0x64, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x1a, 0x65,
	0x0a, 0x0d, 0x53, 0x68, 0x61, 0x72, 0x64, 0x41, 0x6e, 0x64, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x12,
	0x0e, 0x0a, 0x02, 0x76, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x76, 0x63, 0x12,
	0x14, 0x0a, 0x05, 0x73, 0x68, 0x61, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05,
	0x73, 0x68, 0x61, 0x72, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x31, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x06, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x31, 0x12, 0x16, 0x0a,
	0x06, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x32, 0x18, 0x04, 0x20, 0x03, 0x28, 0x03, 0x52, 0x06, 0x70,
	0x72, 0x6f, 0x6f, 0x66, 0x32, 0x22, 0x31, 0x0a, 0x03, 0x44, 0x65, 0x63, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08,
	0x64, 0x65, 0x63, 0x53, 0x68, 0x61, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08,
	0x64, 0x65, 0x63, 0x53, 0x68, 0x61, 0x72, 0x65, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x3b, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_Message_proto_rawDescOnce sync.Once
	file_Message_proto_rawDescData []byte
)

func file_Message_proto_rawDescGZIP() []byte {
	file_Message_proto_rawDescOnce.Do(func() {
		file_Message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Message_proto_rawDesc), len(file_Message_proto_rawDesc)))
	})
	return file_Message_proto_rawDescData
}

var file_Message_proto_msgTypes = make([]protoimpl.MessageInfo, 44)
var file_Message_proto_goTypes = []any{
	(*Message)(nil),               // 0: Message
	(*NewMessage)(nil),            // 1: NewMessage
	(*OptRBCMessage)(nil),         // 2: OptRBCMessage
	(*OSVMessage)(nil),            // 3: OSVMessage
	(*SS24Share)(nil),             // 4: SS24Share
	(*ElgamalEncShare)(nil),       // 5: ElgamalEncShare
	(*AESEncShare)(nil),           // 6: AESEncShare
	(*AESEncMultiShare)(nil),      // 7: AESEncMultiShare
	(*Poly)(nil),                  // 8: poly
	(*ChallengePoly)(nil),         // 9: challengePoly
	(*DKGMessage)(nil),            // 10: DKGMessage
	(*DKGShareMessage)(nil),       // 11: DKGShareMessage
	(*DisperseData)(nil),          // 12: DisperseData
	(*BroadcastMessage)(nil),      // 13: BroadcastMessage
	(*HartsMessage)(nil),          // 14: HartsMessage
	(*HartsHavssMessage)(nil),     // 15: HartsHavssMessage
	(*HartsCommitMessage)(nil),    // 16: HartsCommitMessage
	(*InnerProductProof)(nil),     // 17: InnerProductProof
	(*NizkIPAProof)(nil),          // 18: NizkIPAProof
	(*HartsRowVectorMessage)(nil), // 19: HartsRowVectorMessage
	(*HartsColumnMessage)(nil),    // 20: HartsColumnMessage
	(*HartsProposeSet)(nil),       // 21: HartsProposeSet
	(*RAMessage)(nil),             // 22: RAMessage
	(*ASKSMessage)(nil),           // 23: ASKSMessage
	(*ASKSHashVector)(nil),        // 24: ASKSHashVector
	(*IGMessage)(nil),             // 25: IGMessage
	(*ICGMessage)(nil),            // 26: ICGMessage
	(*PreIRBCMessage)(nil),        // 27: PreIRBCMessage
	(*Value)(nil),                 // 28: Value
	(*Echo)(nil),                  // 29: Echo
	(*Lock)(nil),                  // 30: Lock
	(*Finish)(nil),                // 31: Finish
	(*Done)(nil),                  // 32: Done
	(*Halt)(nil),                  // 33: Halt
	(*PreVote)(nil),               // 34: PreVote
	(*Vote)(nil),                  // 35: Vote
	(*Proposal)(nil),              // 36: Proposal
	(*BLock)(nil),                 // 37: BLock
	(*BLockSetValue)(nil),         // 38: BLockSetValue
	(*BLockSetValidation)(nil),    // 39: BLockSetValidation
	(*Call)(nil),                  // 40: Call
	(*Help)(nil),                  // 41: Help
	(*Dec)(nil),                   // 42: Dec
	(*Help_ShardAndProof)(nil),    // 43: Help.ShardAndProof
}
var file_Message_proto_depIdxs = []int32{
	6,  // 0: AESEncMultiShare.aesEncShares:type_name -> AESEncShare
	5,  // 1: AESEncMultiShare.elGamalEncShares:type_name -> ElgamalEncShare
	8,  // 2: challengePoly.polys:type_name -> poly
	17, // 3: NizkIPAProof.ipaProof:type_name -> InnerProductProof
	18, // 4: HartsRowVectorMessage.pi_i:type_name -> NizkIPAProof
	18, // 5: HartsColumnMessage.p_ij:type_name -> NizkIPAProof
	43, // 6: Help.shardAndProof:type_name -> Help.ShardAndProof
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_Message_proto_init() }
func file_Message_proto_init() {
	if File_Message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Message_proto_rawDesc), len(file_Message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   44,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Message_proto_goTypes,
		DependencyIndexes: file_Message_proto_depIdxs,
		MessageInfos:      file_Message_proto_msgTypes,
	}.Build()
	File_Message_proto = out.File
	file_Message_proto_goTypes = nil
	file_Message_proto_depIdxs = nil
}
