syntax = "proto3";

option go_package = ".;protobuf";

message Message {
  string type = 1;// instance id
  bytes id = 2;
  uint32 sender = 3;
  bytes data = 4;
}

message NewMessage {
  string protocol = 1;
  string instanceID = 2;
  int64 fromID = 3;
  int64 destID = 4;
  bytes data = 5;
}

message OptRBCMessage {
  int64 msgType = 1;
  string sessionID = 2;
  int64 fromID = 3;
  int64 destID = 4;
  bytes payload = 5;
}

message OSVMessage {
  int64 fromID=1;
  int64 destID=2;
  string instanceID=3;
  string msgType=4;
}

// modified SS24 protocol message
// 1. ss24 share
message SS24Share{
  string instanceID = 1;
  int64 index =2;
  repeated bytes fShare = 3;
  repeated bytes gShare = 4;
}

// 2. internal
message ElgamalEncShare {
  int64 index =1;
  bytes c1 = 2;
  bytes c2 = 3;
}

// 3. internal
message AESEncShare {
  int64 index = 1;
  bytes cipher =2;
}

// 4. internal
message AESEncMultiShare {
  repeated AESEncShare aesEncShares = 1;
  repeated ElgamalEncShare elGamalEncShares = 2;
}

// 5. internal
message poly{
  repeated bytes coefficient = 1;
}

// 6. internal
message challengePoly {
  repeated poly polys = 1;
}

// batch DKG protocol message
message DKGMessage{
  int64 fromID=1;
  int64 destID=2;
  string instanceID=3;
  int64 index = 4;
  bytes value = 5;
}

// internal
message DKGShareMessage{
  int64 index=1;
  bytes vj =2;
}

// opt broadcast message
message DisperseData{
  bytes myStripe =1;
  bytes senderStripe =2;
}

message BroadcastMessage {
  string type = 1;// instance id
  int64 instanceID = 2;
  int64 fromID = 3;
  bytes data = 4;
}

// harts protocol message
message HartsMessage {
  int64 fromID=1;
  int64 destID=2;
  string instanceID=3;
  string type = 4;
  bytes value = 5;
}

message HartsRowSingle{
  repeated bytes c_i = 1;
  repeated bytes pi_i = 2;
}

message HartsRow{
  int64 index = 1;
  repeated HartsRowSingle rows = 2;
}

// validated aba protocol message
message RAMessage{
  int64 fromID=1;
  int64 destID=2;
  string instanceID=3;
  string type = 4;
  bytes value = 5;
}

// Asynchronous Secret Key Sharing protocol message
message ASKSMessage{
  int64 fromID=1;
  int64 destID=2;
  string instanceID=3;
  string type = 4;
  bytes value = 5;
}

// internal ASKS hash vector
message ASKSHashVector{
  repeated bytes hashByte=1;
}

// Index Gather protocol message
message IGMessage {
  int64 fromID = 1;
  int64 DestID = 2;
  string instanceID = 3;
  string type = 4;
  repeated int64 set = 5;
}

// provable broadcast
message Value{
  bytes value = 1;// paload
  bytes validation = 2;// for external validating
}
message Echo{
  bytes sigshare = 1 ;
}

// smvba
message Lock{
  bytes value = 1;
  bytes sig = 2;
}
message Finish{
  bytes value = 1;
  bytes sig = 2;
}
message Done{
  bytes coinShare = 1 ;
}
message Halt{//Halt:=<Finish> of the round-leader
  bytes value = 1;
  bytes sig = 2;
}
message PreVote{
  bool vote = 1;
  bytes value = 2;
  bytes sig = 3;
}
message Vote{
  bool vote = 1;
  bytes value =2;
  bytes sig =3;
  bytes sigshare = 4;
}


//sDumbo
message Proposal{
  bytes tx = 1;
  repeated uint32 view = 2;
}

message BLock{
  bytes hash = 1;
  bytes sig = 2;
}

message BLockSetValue{
  repeated uint32 pid = 1;
  repeated bytes hash = 2;
}
message BLockSetValidation{
  repeated bytes sig = 1;
}

message Call{
  repeated uint32 indices = 1;
}
message Help{
  message ShardAndProof{
    bytes vc = 1;
    bytes shard =2;
    repeated bytes proof1 = 3;
    repeated int64 proof2 = 4;
  }
  repeated uint32 indices = 1;
  repeated ShardAndProof shardAndProof = 2;
}

//TSE
message Dec{
  uint32 id = 1;
  bytes decShare = 2;
}
